### ISSUE TITLE
Unable to read a bytes object

### ISSUE THREAD

**Issue by Mitalee** [python-amazon-mws/python-amazon-mws#102]
Hi, 

While using the reports api, the following was returned

```
>>> r.parsed
b'PK\x03\x04\x14\x00\x08\x08\x08\x00dy#N\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00MTR_B2C-DECEMBER-2018.csv'
>>> type(r)
<class 'mws.mws.DataWrapper'>
>>> type(r.original)
<class 'bytes'>
```

both csv.reader and pandas are unable to read this object. Any help is appreciated.

Regards

**Comment by elcolumbio** [comment]
If you are on the develop branch you could use your own contribution with: r.unzipped
or i think r.text should work as well.
But i am not too sure about this.

**Comment by Mitalee** [comment]
Hi Florian,

Assuming you're talking about 'r' as a response object, I think the requests library does not have an 'unzip' command. I tried both your suggestions on the master branch. 

```
    print('DATA UNZIPPED IS:', response.unzipped)
AttributeError: 'Response' object has no attribute 'unzipped'
```
I did examine the headers of the response which indicated that the report content-type is 'application/zip'. But there are some extra characters in there and ZipFile is unable to unzip it.

```
>>> f.original
b'PK\x03\x04\x14\x00\x08\x08\x08\x00dy#N\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00MTR_B2C-DECEMBER-2018.csv'

DATA TEXT IS: dy#NMTR_B2C-DECEMBER-2018.csv

zipfile.BadZipFile: File is not a zip file
```

Is there a character encoding issue?

**Comment by Mitalee** [comment]
Hi All,

I'm going to close this because it's not an error from our library. 

If there are enough developers who need the response headers, I'd be glad to put in code for the same. Until then, I am just using the editable version of the library.

Thanks again..
