### ISSUE TITLE
Guaranteeing that an order is new

### ISSUE THREAD

**Issue by tchoedak** [python-amazon-mws/python-amazon-mws#103]
This may not be terribly relevant to this project, but I have a feeling this project's users are likely to be most informed about this stuff.

When using the ListOrders endpoint and receiving orders informations, how do folks typically ensure that an order is new?

Is it sufficient just to hit the ListOrders API and check for any *new* AmazonOrderIds where new can be determined by checking if those AmazonOrderIds exist in some DB that your storing orders in?

It seems to me almost every new order goes into a `Pending` status. Is it then more accurate to use the method above, but also check for OrderStatus == 'Pending'?

BTW love the work put into this project and i've been leveraging it in my own personal project (tchoedak/anoti) to send notifications on new orders (hence this question).

**Comment by GriceTurrble** [comment]
*Disclaimer: I have not used the Orders API myself and do not have a seller account to test with at this time; I am basing the following on [documentation](http://docs.developer.amazonservices.com/en_US/orders-2013-09-01/Orders_ListOrders.html) and prior knowledge of related APIs.*

You can make requests for orders within datetime ranges by passing parameters for `CreatedAfter` and `CreatedBefore`, to check for orders that are created between those times (CreatedAfter < CreatedBefore). If you run the request periodically and adjust the datetime range as needed, you should be able to capture all recently-created orders, and from there you can compare with internal data to find what's "new".

Outside that, you would want to request using `LastUpdatedAfter` and `LastUpdatedBefore` to ensure your internal versions of all orders are up-to-date. Simply run that on a schedule and set your time window a bit larger than that schedule's recurrence (say, if you run every hour, set it to 3 or 6 hours, just in case you have some periodic downtime; and perhaps plan out some contingencies where you might need to check the past 12 hours or more, if you have a longer outage). Use the returned date to compare to your internal data, seeing if your internal data's timestamp is different from that of the returned order, and updating accordingly.

Doing that, if you keep track of those orders internally, then any time you encounter a new OrderId, you know you have a new order.

**Comment by Bobspadger** [comment]
@GriceTurrble has explained pretty much exactly how we do it (in a far more articulate and precise way than I ever could)

I think this is more of a 'how do I use the module' rather than 'something is not working as anticipated' and could probably be closed?

Is it worth writing items up like this in the docs?

**Comment by tchoedak** [comment]
@GriceTurrble Perfect, I'm implementing data ingestion now into a DB using your advice. @Bobspadger you're correct that this is just a how-to question, but I imagine its a common one new users of this lib will be asking. Whether this belongs in the docs - i'm not sure :P.
