### ISSUE TITLE
more tests

### ISSUE THREAD

**Issue by elcolumbio** [python-amazon-mws/python-amazon-mws#107]
We could write more tests to make it more stable and less random.
I have 3 ideas on top of my mind:
- write some parameterized tests, to test more possibilities for every api type.

for the 2 other we could parse all the example requests and responses from the official docs.
And dump them in one big file.
- for requests we could write tests cases to rebuild those xml requests

- for responses, we could use the responses and define how they should look like after we parse the response.

Do you think especially the last two are a good idea?
I would have some fun doing it anyway i guess.
Since i hope to parse it all in one go. Writing the tests is probably more time consuming.

**Comment by jameshiew** [comment]
Syntactic tests would be nice, at the very least a smoke test of some sort that we can produce a simple request and parse a simple response, for some meaning of simple :) I can see there is a yet unused `tests/example_response.txt` fixture in the `develop` branch that we could be used for this.

There are actually XSD schema that could be used to generate example requests/responses (an example here - https://github.com/pgrimaud/amazon-mws-xsd - though these may be out of date). We could even use such to validate requests/responses, potentially.

**Comment by Mitalee** [comment]
testing the responses is a great idea, I find that most of the times I'm not able to figure out the content-type of the reports. I can help with that.

**Comment by GriceTurrble** [comment]
Got a whole lot more testing added in with recent changes to `develop`, especially some additions in #207 . Still need a full test that covers the entire request cycle past testing parameters (as most tests stop there), but will deal with that separately in the near future.
