### ISSUE TITLE
Change item's quantity

### ISSUE THREAD

**Issue by Sneerbol** [python-amazon-mws/python-amazon-mws#108]
I need find item by name and change item's quantity to zero(for example)
So... Can I do it with python-amazon-mws ? If I can please - help me  with code :)

**Comment by Bobspadger** [comment]
Can you give a bit more information on this?

Why do you need to find an item by name? surely you have the ASIN / SKU in your back office system?

If you need to change the price of something, then the feeds API is what you need to send an update for the product.

**Comment by Sneerbol** [comment]
I buy t-shirts, socks and other... I have the site with these goods from my seller, and if my seller doesn't have goods, for example socks, I must change quantity to zero, sometimes I can't do it manually, and this is not good if somebody buys goods that I don't have (amazon reduces my rating )

**Comment by Bobspadger** [comment]
Then I would suggest building yourself an intermediary system where you map your suppliers part code to an ASIN, then query by that?

**Comment by Sneerbol** [comment]
I like it

**Comment by Sneerbol** [comment]
but I still need function that can change item quantity to zero 🗡

**Comment by Bobspadger** [comment]
I do it this way:

```py
result = feeds_api.submit_feed(feed_data, '_POST_FLAT_FILE_INVLOADER_DATA_')
```

with the content of the `feed_data` being made up of the SKU code (or ASIN) and quantity.

Feeds API docs:
https://developer.amazonservices.co.uk/gp/mws/api.html/260-0080379-7629142?ie=UTF8&group=bde&section=feeds&version=latest

```

feed_data = """
sku\tquantity\tmerchant-shipping-group-name\n```
mysku1\t0\my_shipping_group\n
"""
```

You don't need to actually create file, you can create a file like object in memory (`feed_data`) and just send it

**Comment by Sneerbol** [comment]
I understand bad this code :( 
Could you explain please ? )
For example I have ASIN = ".........."
And What I need  change in your code to edit quantity of this product to zero by ASIN
?

**Comment by Bobspadger** [comment]
The change would just be `ASIN quantity etc` in the header, and 0 for the value provided.

**Comment by Bobspadger** [comment]
I think we can consider this issue closed now ?

**Comment by Sneerbol** [comment]
You helped me, but I think that I cannot be able to  write this soft. You have explained me  a process, I don't realize how to write it in python code, I'd want your example, if you have time of course...
For example, the ASIN for Hasbro's "Monopoly" game is B00005N5PF. And I sell Monopoly, and my supplier don't have it, I must change quantity to zero. I don't know why Amazon doesn't have python examples of code :( has php, c++, java ... but not python =(

**Comment by Bobspadger** [comment]
This module is community written, developed and supported and has nothing to do with Amazon so they won't have any docs or examples I'm afraid.

Reading their generic API documents should be most of what you or your developer need to get going if you wish to use this module.

If you are unable to write Python, but would like to learn, I'd highly recommend going and doing a couple of courses online to get the basics, you should get running in no time. (codeacademy etc)

I'm happy to help with issues arising from the code not working as expected, and to give a helping hand, but actually telling / doing is probably outside the scope of the support offered here.

If you start on this project and get stuck, by all means feel free to ask specific questions and I'll be glad to help where / when I can :)

Good luck - Python is a great language to learn, but also a fantastic language to get stuff done with - I'm sure you will enjoy the journey!

Alex

**Comment by Sneerbol** [comment]
Thanks

**Comment by Bobspadger** [comment]
#21 may give you more insight into how this is done from the amazon api perspective - hope it helps.
