### ISSUE TITLE
inventory cannot get Canada data

### ISSUE THREAD

**Issue by bobohope** [python-amazon-mws/python-amazon-mws#109]
list_inventory_supply should have marketplaceid as a parameter

**Comment by Bobspadger** [comment]
Looking at the docs:

http://docs.developer.amazonservices.com/en_US/fba_inventory/FBAInventory_ListInventorySupply.html

It seems it is only required for NA (North America?)

Shouldn't be too hard to do if someone has the time ?

**Comment by nishilchen** [comment]
I added the update code in the list_inventory_supply, but still get inventory in US.
`
def list_inventory_supply(self, skus=(), marketplaceids = None, datetime_=None,
                              response_group='Basic', next_token=None):
        """
        Returns information on available inventory
        """

        data = dict(Action='ListInventorySupply',
                    QueryStartDateTime=datetime_,
                    ResponseGroup=response_group,
                    )
        data.update(utils.enumerate_param('SellerSkus.member.', skus))
        data.update(utils.enumerate_param('MarketplaceIdList.Id.', marketplaceids))
        return self.make_request(data, "POST")
`

**Comment by Bobspadger** [comment]
You only need to send the marketplace_id, not all of them

**Comment by Bobspadger** [comment]
```
def list_inventory_supply(self, skus=(), marketplace_id=None, datetime_=None,
                              response_group='Basic', next_token=None):
```
```
data = dict(Action='ListInventorySupply',
                    QueryStartDateTime=datetime_,
                    ResponseGroup=response_group,
                    MarketplaceId=marketplace_id
                    )
```

**Comment by nishilchen** [comment]
Error occurs:
```

  File "C:\Users\Anaconda3\lib\urllib\parse.py", line 814, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")

TypeError: quote_from_bytes() expected bytes

```

**Comment by bobohope** [comment]
look at my repo, I foredk this and change it there. it's working. I just never get a pull request....... my GitHub is called bobohope Sent from my Huawei phone-------- Original Message --------Subject: Re: [python-amazon-mws/python-amazon-mws] inventory cannot get Canada data (#109)From: Li Hsin Chen To: python-amazon-mws/python-amazon-mws CC: Bobohope ,Author Error occurs:

  File "C:\Users\Anaconda3\lib\urllib\parse.py", line 814, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")

TypeError: quote_from_bytes() expected bytes

**Comment by bobohope** [comment]
not only North America. because Amazon open Japan Australia Europe market place... if you have the SAME sku in different market place ,you need to use marketplaceid as parameter as well otherwise you are gonna get the US data. Also, these marketplace might need different account ID. you may need to request a new one from Amazon to access Japan data Australia data and   ...Sent from my Huawei phone-------- Original Message --------Subject: Re: [python-amazon-mws/python-amazon-mws] inventory cannot get Canada data (#109)From: Li Hsin Chen To: python-amazon-mws/python-amazon-mws CC: Bobohope ,Author Error occurs:

  File "C:\Users\Anaconda3\lib\urllib\parse.py", line 814, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")

TypeError: quote_from_bytes() expected bytes

**Comment by Bobspadger** [comment]
This is now in the develop branch if you want to check it @bobohope
