### ISSUE TITLE
MWS Encryption

### ISSUE THREAD

**Issue by xlcheese** [python-amazon-mws/python-amazon-mws#117]
Does this use encryption as required by Amazon?  

https://docs.developer.amazonservices.com/en_US/dev_guide/DG_DataProtectionPolicy.html

Amazon Policy:  Encryption in Transit. Developers must encrypt all Amazon Information in transit (e.g., when the data traverses a network, or is otherwise sent between hosts. This can be accomplished using HTTP over TLS (HTTPS). Developers must enforce this security control on all applicable external endpoints used by customers as well as internal communication channels (e.g., data propagation channels among storage layer nodes, connections to external dependencies) and operational tooling. Developers must disable communication channels which do not provide encryption in transit even if unused (e.g., removing the related dead code, configuring dependencies only with encrypted channels, and restricting access credentials to use of encrypted channels). Developers must use data message-level encryption (e.g., using AWS Encryption SDK) where channel encryption (e.g., using TLS) terminates in untrusted multi-tenant hardware (e.g., untrusted proxies).

**Comment by Bobspadger** [comment]
https://github.com/python-amazon-mws/python-amazon-mws/blob/3253eaacfc55d6180cfed2ba3d2c1194e3ad3b55/mws/mws.py#L44

You can see that the marketplace URLS are all https.

**Comment by xlcheese** [comment]
Thanks for pointing it out!
