### ISSUE TITLE
Orders details to file

### ISSUE THREAD

**Issue by nicolaerario** [python-amazon-mws/python-amazon-mws#119]
Full details of an order are divided into two separate requests:
listOrders and listOrderItems;
what code do you use to have a file with the details of the customer and his order in a single file?
Moreover, the XML generated by the requests are quite nested and therefore difficult to manage

**Comment by Bobspadger** [comment]
We download the orders and store them in a MySQL db.

I have the following tables:

`amazonorder`
`amazonorderaddress`
`amazonorderitem`

This allows me to represent the amazon order in a related way.

You could effectively output this as JSON if you need a flat file, but more information on what you are intending to do with it would really be needed.

We use a `list_orders` and `get_order` with `list_order_items`

**Comment by Bobspadger** [comment]
@nicolaerario do you mind if I close this issue now as its kind of outside the scope of the project?

**Comment by nicolaerario** [comment]
Sure, no problem!
