### ISSUE TITLE
How to update features, description and title?

### ISSUE THREAD

**Issue by JasonCrowe** [python-amazon-mws/python-amazon-mws#120]
I need to create a system that will update the features, description, and title of thousands of items. It's probably obvious why I don't want to do this in Seller Central. 🤣

Is this possible through the API?

**Comment by Bobspadger** [comment]
Yes, it should be.

The fun is matching the template to the produt, although I have found they seem to accept my single template for all products.

**Comment by JasonCrowe** [comment]
I am lucky that all the products will be in the same category. 🤣

**Comment by elcolumbio** [comment]
Have you been succesful and where there any learnings? Happy to hear :) .

**Comment by JasonCrowe** [comment]
The project never came to be. Unfortunately, there was nothing learned.
