### ISSUE TITLE
Reports - XMLError

### ISSUE THREAD

**Issue by alixleger** [python-amazon-mws/python-amazon-mws#128]
When I use the get_report function of the Reports API, xml.etree.ElementTree.ParseError is raised while it must be handled line 255 of mws.py.

The only solution I found is to import directly ElementTree like that : 

```python
from xml.etree import ElementTree
try:
    # python 2.7+
    # pylint: disable=no-member
    XMLError = ElementTree.ParseError
except ImportError:
    # python 2.6-
    # pylint: disable=no-member
    from xml.parsers import expat
    XMLError = expat.ExpatError 
```
instead of : 

```python
try:
    from xml.etree.ElementTree import ParseError as XMLError
except ImportError:
    from xml.parsers.expat import ExpatError as XMLError
```

in the mws.py file. Do you have an other solution ?

**Comment by Bobspadger** [comment]
I'm assuming you are using the main branch. Have you tried the develop version (I don't think anything has changed with relation to this part of the code, but its worth a try)

Also @elcolumbio has been doing some work on changing how the dictionaries are created / xml parsed. His branch / PR may also help in this instance.

**Comment by cohlar** [comment]
Hi, thanks for the work-around!
