### ISSUE TITLE
Whether parameters can be provided to remove the "value" node from each layer

### ISSUE THREAD

**Issue by probeyang** [python-amazon-mws/python-amazon-mws#130]
The interface provided by boto does not have the "value" node in each layer. I use it work very well, but it have not finance interface. so now i start to use python-amazon-mws , but it adds a node to every layer of my interface. The original structure is very complex. I don't want to traverse another layer.

**Comment by Bobspadger** [comment]
Hi, Could you add a bit more info to explain your issue please? Are you talking about the returned data from Amazon MWS?

**Comment by probeyang** [comment]
> Hi, Could you add a bit more info to explain your issue please? Are you talking about the returned data from Amazon MWS?

thank you for your reply :)

i mean, for example:
![image](https://user-images.githubusercontent.com/18691244/66793551-7b714400-ef30-11e9-8199-74a5f786cc96.png)
this order api, and got result is:
`{'value': '\n    ', 'Status': {'value': 'GREEN'}, 'Timestamp': {'value': '2017-06-14T16:39:12.765Z'}}`
i just want to get result is:
`{'Status': 'GREEN', 'Timestamp':'2017-06-14T16:39:12.765Z'}`
I found that boto is like this, but it does not provide the finances interface.

thanks a lot

**Comment by Bobspadger** [comment]
@probeyang I think this is most probably a duplicate request of #69 where there is a much larger discussion going on.

We do need to put some more effort / time into moving on with the 1.0 release, which may well fix this request.

Its very close, but really requires some overview from @GriceTurrble and @jameshiew to get there (sorry chaps, I know life etc!)

If you don't mind, I'll mark this as duplicate and close?

**Comment by probeyang** [comment]
> @probeyang I think this is most probably a duplicate request of #69 where there is a much larger discussion going on.
> 
> We do need to put some more effort / time into moving on with the 1.0 release, which may well fix this request.
> 
> Its very close, but really requires some overview from @GriceTurrble and @jameshiew to get there (sorry chaps, I know life etc!)
> 
> If you don't mind, I'll mark this as duplicate and close?

it's Really duplicate, you can close it, I don't mind。 thanks a lot. In addition, I want to say, when can this future be handled? :)

**Comment by Bobspadger** [comment]
@probeyang its already kind of in the merge request (iirc)

I think the discussion was around the fact that sometimes you need the `value` key (without re-reading the entire discussion)

**Comment by probeyang** [comment]
> @probeyang its already kind of in the merge request (iirc)
> 
> I think the discussion was around the fact that sometimes you need the `value` key (without re-reading the entire discussion)

ok , thanks
