### ISSUE TITLE
Stop support of Python2

### ISSUE THREAD

**Issue by Bobspadger** [python-amazon-mws/python-amazon-mws#131]
https://pythonclock.org

We have less than 2 months left.

I know we discussed dropping it, but we are so close to D-Day for python2 that it seems silly to have to add in extra logic and tests etc for it.

Those who must run python2 can stick with the current version?

**Comment by JasonCrowe** [comment]
I am just a user, but I don't see any value in supporting python 2.

**Comment by GriceTurrble** [comment]
Current `develop` version no longer supports Python2, and hasn't for some time. Closing this. Thank you!
