### ISSUE TITLE
RequestReport with csv as the output

### ISSUE THREAD

**Issue by norus** [python-amazon-mws/python-amazon-mws#132]
Has anyone looked into requesting reports and specifying the response format as csv?
It seems it's not really supported (https://docs.developer.amazonservices.com/en_UK/reports/Reports_RequestReport.html) although it is supported in the seller central UI:
![Screen Shot 2019-10-17 at 2 26 45 PM](https://user-images.githubusercontent.com/234848/67009249-858b7200-f0eb-11e9-95c6-5e4a0ee04072.png)

**Comment by Bobspadger** [comment]
The reports are provided as per amazon?

http://docs.developer.amazonservices.com/en_US/reports/Reports_GetReport.html

Amazon state they come out as per the report type

They also show the reports available her:

http://docs.developer.amazonservices.com/en_US/reports/Reports_ReportType.html

and the format of the report

**Comment by dsiq-rd** [comment]
You can convert most reports by using pandas into CSV from tab delimited file.
