### ISSUE TITLE
defusedxml and MWS CSV reports

### ISSUE THREAD

**Issue by jerry40** [python-amazon-mws/python-amazon-mws#135]
Hi!

I noticed that if some lib uses this code: `from defusedxml import ElementTree` , Amazon csv reports stop working with 
```
  File ".env/lib/python3.6/site-packages/mws/mws.py", line 429, in get_report
    return self.make_request(data)

  File ".env/lib/python3.6/site-packages/mws/mws.py", line 255, in make_request
    parsed_response = DictWrapper(response.text, rootkey)

  File ".env/lib/python3.6/site-packages/mws/mws.py", line 109, in __init__
    self._mydict = utils.XML2Dict().fromstring(remove_namespace(xml))

  File ".env/lib/python3.6/site-packages/mws/utils.py", line 106, in fromstring
    text = ET.fromstring(str_)

  File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)

  File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 1626, in feed
    self._raiseerror(v)

  File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 1525, in _raiseerror
    raise err

  File "<string>", line unknown
ParseError: syntax error: line 1, column 0
```

This catch is not working, it can't catch ParseError wihch is aliased with XMLError:

```
            except XMLError:
                parsed_response = DataWrapper(data, response.headers)
```

I have a piece of code which shows a problem:
```
# from defusedxml import ElementTree
from xml.etree.ElementTree import ParseError as err1
import xml.etree.ElementTree
a = err1()
b = xml.etree.ElementTree.ParseError()
a
b
type(a)
type(b)
type(a) == type(b)
```
Uncomment the first line and see the difference

**Comment by elcolumbio** [comment]
Hi @jerry40.
I did some investigation and can confirm what you described.
I am not familiar with this and defusedxml, but it seems they are using by default the Cython code from the DLL?
After reading the uncomfirmed defusedxml PR 40 it looks like this is the right behavior.
He is even testing for the difference:
self.assertIsNot(pymod.ParseError, ElementTree.ParseError)
As a solution: if you parse with defusedxml you have to import the ParseError also from defusedxml.
If you find something out, i am happy to learn something new.

**Comment by Bobspadger** [comment]
Sorry for being late to the party here, but from my quick reading, is this an mws issue, or a defusedxml issue ?

**Comment by jerry40** [comment]
@elcolumbio , I'm not familiar with defusedxml too, I think it somehow 'hides' standard python xml classes and methods to make everything more safe. So far we just copy mws code in a standalone .py file and make some changes there:

```
import xml.etree.ElementTree
from xml.etree.ElementTree import ParseError as XMLError

            except XMLError:
                parsed_response = DataWrapper(data, response.headers)

            except xml.etree.ElementTree.ParseError:
                parsed_response = DataWrapper(data, response.headers)
```

@Bobspadger , in my opinion the issue is in mws lib. Even python docs say something like 'if you want to work with xml safely, use defusedxml bla bla bla'. So it is possible situation when a developer uses mws and defusedxml at same time. In this case, mws will try to parse csv as xml.

**Comment by elcolumbio** [comment]
@Bobspadger Yes it's a defusedxml 'user issue' and not a mws bug.

**Complicated explanation:**
In python 3 xml.etree.ElementTree is shadowing the python code with the c optimized version (whenever available, assume always). But defusedxml needs access to the python version.
To solve this they are invalidating the module cache. To explain what is happening the python docs are helpful:
https://docs.python.org/3/reference/import.html#the-module-cache
> Beware though, as if you keep a reference to the module object, invalidate its cache entry in sys.modules, and then re-import the named module, the two module objects will not be the same.

In your example you are referencing to an invalidated module cache, except in your proposed fix you actually refer to the defusedxml anyway, because it's looking for it in the new cache.

**Simple solution for you and in general:**
If you decide to use defusedxml never import the xml.etree.ElementTree library, they are not the same object. Instead use explicitly the exception from defusedxml.
```python3
from defusedxml import ParseError as XMLError
```
