### ISSUE TITLE
apis folder missing with pip install of develop branch

### ISSUE THREAD

**Issue by kenlittleton** [python-amazon-mws/python-amazon-mws#139]
It seems the 'apis' folder is not installed when using pip to install the develop branch from github.

`pip install git+https://github.com/python-amazon-mws/python-amazon-mws.git@develop#egg=mws`

**Exception:**  _ModuleNotFoundError: No module named 'mws.apis'_

**Workaround:**  Download develop branch and copy the api folder into your virtual environment.

**Alternate:**  Installs into a src folder in your virtual environment.

`pip install -e git://github.com/python-amazon-mws/python-amazon-mws.git@develop#egg=mws`

**Comment by elcolumbio** [comment]
good catch @kenlittleton. It is one of the few known bugs. I can redo this today #106.

**Comment by Bobspadger** [comment]
@elcolumbio if you can get it done today I should have time to test and approve

**Comment by Bobspadger** [comment]
This is now fixed thanks to @elcolumbio and in the develop branch - install away!
