### ISSUE TITLE
Add Amazon NL region to Marketplaces Enum

### ISSUE THREAD

**Issue by ceijssen** [python-amazon-mws/python-amazon-mws#145]
Hi there,

Amazon is currently expanding its business to the Netherlands and I've received their NL marketplace ID. I'm not really familiar with contributing to this project, so I preferred creating an issue instead :sweat_smile: I think the only line needed to add to the `Marketplaces(Enum)` class in `mws/mws.py` is the following:

`NL = ('https://mws-eu.amazonservices.com', 'A1805IZSGTT6HS')`

Not sure if it needs to be added elsewhere too. 

Would appreciate if this could be added :-)

**Comment by Bobspadger** [comment]
Hi @ceijssen I'm happy to sort this out, do you have a link to the docs for this Marketplace ID?

I'm checking their dev guide and its currently not listed. (Its not that I do not believe you!) but I'd like to just confirm its correct before adding.

Do you have any supporting docs from Amazon and I'll sort it out.

Cheers

Alex

**Comment by ceijssen** [comment]
Hi @Bobspadger thanks for the quick reply :-) I got it through an email from a contact at Amazon, I see it's not in the docs yet so I'll ask the contact if/when they can add it to the docs.

**Comment by Bobspadger** [comment]
No problem.

If they have some info somewhere then I'll get on it.

It will most likely be in the develop branch - I'm not sure what version you are using ?

**Comment by ceijssen** [comment]
We're using 0.8.6. I'll try to find some online resources that mention the NL ID, I see our guy is on vacation now so it might take some time.

**Comment by Martijn-Kraan** [comment]
@Bobspadger Hey there! I noticed you were waiting on confirmation about the Amazon NL Marketplace ID. Our correspondent from Amazon just emailed me to confirm that the ID provided by @ceijssen is the correct one. See this screenshot from the email I received from them. 

![image](https://user-images.githubusercontent.com/32834766/73356216-1ef52300-429a-11ea-9cd7-e48774fee655.png)

Could you add this to the configuration?

**Comment by Bobspadger** [comment]
@Martijn-Kraan I've just merged this into Develop for you - is that ok?

**Comment by Bobspadger** [comment]
@Martijn-Kraan happy for me to close this now?

**Comment by Martijn-Kraan** [comment]
@Bobspadger Yes sure! Could you give me an indication here on when this will be on the production branch?

**Comment by Bobspadger** [comment]
ah, ok, I'll take a look and see

**Comment by p-nilsson** [comment]
@Bobspadger I see that The Netherlands is now listed in the [marketplace webservices documentation](https://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html) Do you have any indication when it will be in the production branch as well?

**Comment by Bobspadger** [comment]
@p-nilsson @ceijssen this is now done and in the master branch. I have just uploaded it to pypi as well.
