### ISSUE TITLE
Finish InboundShipments API

### ISSUE THREAD

**Issue by jameshiew** [python-amazon-mws/python-amazon-mws#15]
http://docs.developer.amazonservices.com/en_UK/fba_inbound/index.html

**Comment by GriceTurrble** [comment]
Progress made with #33 , though there are some missing methods. #22 will provide more complete coverage, pending changes.

**Comment by GriceTurrble** [comment]
#22 updated and merged to develop branch.

One method in that PR, `put_transport_content`, is incomplete: the one merged only included details for one type of TransportDetail (`NonPartneredSmallParcelData`), but there are 4 types to be considered. Some more work is needed there to complete it.

**Comment by GriceTurrble** [comment]
Minor bump, still need to work on `put_transport_content` to complete this API. Will commit work on this when I get some free time.
