### ISSUE TITLE
[Announcement] PyCon 2020 Sprints (Apr 20-23, Pittsburgh PA USA)

### ISSUE THREAD

**Issue by GriceTurrble** [python-amazon-mws/python-amazon-mws#150]
Hi folks,

---

**Update 2020-03-12**: [PyCon's blog announced yesterday](https://pycon.blogspot.com/2020/03/march-12-update-on-covid-19.html) they are "exploring options to either reschedule or cancel" the event, in light of the spread of COVID-19.

As such, unless they come out and say "yes it's still on!", I likely won't be attending the conference in person as I planned. But I've still blocked time off work that I intend to use to focus on `python-amazon-mws` development (or "PAM" as I've been calling it).

So, still planning to do sprints and push this project over the hump to 1.0.0. I'll just do it remotely like usual. :)

---

**Original:**

Writing to quickly (*Edit: yeah that worked out great*) announce that I'll be attending [PyCon 2020](https://us.pycon.org/2020/), taking place in Pittsburgh PA USA from April 15 through 23.

Actually I'll really only be attending for the sprints taking place from the 20th through the 23rd (flying home the 24th). A goal of mine is to get focused on `python-amazon-mws` (or perhaps PAM for short? :) ), hopefully drumming up some additional help at the conference and/or participating online, so that we can fix up a number of our outstanding issues and get to a 1.0 version release.

If anyone else watching this space is planning to attend PyCon, let's commiserate here and/or on our [Gitter](https://gitter.im/python-amazon-mws/community) chat (sparse though it may be) and work out some details.

Those helping maintain here, let's take some time over these next couple months to align feature and coverage requests as needed so we can get rolling when the sprints get started.

One major help would be a proper set of docs for the package. Though most of the functionality mirrors MWS, of course; there are some key ways this library can and will augment the API with a touch of OOP and extra tooling. We need more robust documentation to help newer users get started, and that's a great opportunity for new contributors to the project get their toes wet.

I'll keep this space updated with additional details as the conference approaches.

Thanks, and hope to see some folks there!

**Comment by GriceTurrble** [comment]
> This is a test and will be deleted shortly.
<sub>[View in Slack](https://pythonamazonmws.slack.com/archives/CUHKJEKHS/p1582737405001800)</sub>

**Comment by GriceTurrble** [comment]
> Join us on Slack!
<sub>[View in Slack](https://pythonamazonmws.slack.com/archives/CUHKJEKHS/p1582739028002300)</sub>

**Comment by Bobspadger** [comment]
For documentation, is it worth fleshing out some sections that require information to provide a skeleton / framework for filling in as we go?

Is there a nice example of documentation for another project that people find appealing as a template to work from ?

**Comment by agritheory** [comment]
@Bobspadger I don't love [poetry](https://python-poetry.org/docs/) but their docs are among the nicest-looking in the python community. I would also call out [encode](https://www.encode.io/projects/)'s projects generally and the [EdgeDB docs ](https://edgedb.com/docs). All of these are open source so adopting their tooling and/or workflow shouldn't be too hard.

**Comment by GriceTurrble** [comment]
*Update, see original comment.*

**Comment by GriceTurrble** [comment]
Well, that didn't pan out (*thanks, Corona*).

Anyway, I'm wrapping up on a client project, so I'll have some more time to devote here in the coming weeks (as I have for the past few hours today, as well :) ).

Stay safe!
