### ISSUE TITLE
Does anyone know how to use the MerchantFulfillment method?

### ISSUE THREAD

**Issue by Xbeninni** [python-amazon-mws/python-amazon-mws#173]
Hey everyone,

I'm integrating the MerchantFulfillment API into our software, and I use this library. Does anyone know how to use this method? I see this library does include it [here](https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/apis/merchant_fulfillment.py).

Something like below. Input: order detail, Output: a list of shipping rate

```
import mws, os

def getRate(order): 
    merchant_api = mws.MerchantFulfillment(
        access_key= os.environ['MWS_ACCESS_KEY'],
        secret_key= os.environ['MWS_SECRET_KEY'],
        account_id= os.environ['MWS_ACCOUNT_ID'])
   
    # some code here
    response = merchant_api.get_eligible_shipping_services()
```

Thank you!

**Comment by Bobspadger** [comment]
I don't have any specific examples for that I'm afraid. I use the merchant fulfillment for seller fulfilled prime in production here (pretty much all calls but that one!)

I would highly recommend reading Amazon's docs carefully on the flow for these sets of calls as they are very specific.

**Comment by GriceTurrble** [comment]
MWS docs for that section here: https://docs.developer.amazonservices.com/en_US/merch_fulfill/MerchFulfill_Overview.html

Note we are missing one of the methods mentioned in the docs, [GetAdditionalSellerInputs](https://docs.developer.amazonservices.com/en_US/merch_fulfill/MerchFulfill_GetAdditionalSellerInputs.html).

---

Anyway, the `get_eligible_shipping_services` method maps to [GetEligibleShippingServices](https://docs.developer.amazonservices.com/en_US/merch_fulfill/MerchFulfill_GetEligibleShippingServices.html). Their docs in that page are a little sparse, as the request details (on the MWS side) are covered by a [ShipmentRequestDetails datatype](https://docs.developer.amazonservices.com/en_US/merch_fulfill/MerchFulfill_Datatypes.html#ShipmentRequestDetails); whereas our method has essentially an argument for each of these details in the function signature:

https://github.com/python-amazon-mws/python-amazon-mws/blob/b576bcb41d79d0b5ab9b6e75837271c93e84a6f7/mws/apis/merchant_fulfillment.py#L21-L24

Also in our case, some arguments like `package_dimensions` need to be dicts containing all the right keys (see [PackageDimensions datatype](https://docs.developer.amazonservices.com/en_US/merch_fulfill/MerchFulfill_Datatypes.html#PackageDimensions)). We don't perform a transformation on those keys as they're passed in, so you must match the CapCase style of the MWS keys.

---

Given that... I think this method could use some cleanup, similar to the datatype enumerations I started adding into the the Products API ([example commit](https://github.com/python-amazon-mws/python-amazon-mws/commit/ae4942b90bedaee168af75622db14d2f8caf51f4)).

**Comment by Xbeninni** [comment]
Thank you! @GriceTurrble  @Bobspadger 

I used the 0.x version that was installed via ```pip install mws``` and there was no ```MerchantFulfillment``` method. I switched to the develop version and it worked.  Now the problem is, it took 5 minutes to get a response when I ran below code block.

```
import mws, os

sampleOrder = {
	"order_id": '111-2222222-3333333',
	"dimensions": {
	    "Length": '40',
	    "Width": '5',
	    "Height": '5',
	    "Unit": 'inches'
	},
	"weight": {
	    "Value": '60',
	    "Unit": 'ounces'
	},
	"shi_from": {
	    "Name": 'GA Warehouse',
	    "AddressLine1": '123 Main Street',
	    "City": 'Atlanta',
	    "StateOrProvinceCode": 'GA',
	    "PostalCode": '30012',
	    "CountryCode": 'US',
	    "Email": 'john@example.com',
	    "Phone": '8001234567'
	},
	"item_list": [
	    {
	      "OrderItemId": '555265897459',
	      "Quantity": '1'
	    }
	]
}


def getRate(order): 
    merchant_api = mws.MerchantFulfillment(
        access_key= os.environ['MWS_ACCESS_KEY'],
        secret_key= os.environ['MWS_SECRET_KEY'],
        account_id= os.environ['MWS_ACCOUNT_ID'])
    
    order_id = order['order_id']
    dimensions = order['dimensions']
    weight = order['weight']
    ship_from = order['shi_from']
    item_list = order['item_list']

    service_options = {
        "DeliveryExperience": 'DeliveryConfirmationWithoutSignature',
        "CarrierWillPickUp": 'false'
    }

    
    response = merchant_api.get_eligible_shipping_services(amazon_order_id=order_id, seller_order_id=None,
    	                                                        items=item_list, ship_from_address=ship_from,
    	                                                        package_dimensions=dimensions, weight=weight,
    	                                                        must_arrive_by_date=None, ship_date=None,
    	                                                        shipping_service_options=service_options,
    	                                                        label_customization=None)

     print(response.parsed)

if __name__ == "__main__":
	getRate(sampleOrder)
    

```

**Comment by GriceTurrble** [comment]
Response time is almost entirely within Amazon's wheelhouse, unfortunately:
we just fire a request to their backend and await their response. Unless
there's some processing slowdown in building the request content (highly
unlikely), that's not something we can correct without knocking on Amazon's
door. :)

**Comment by Xbeninni** [comment]
Thank you @GriceTurrble  It turns out the ```parsed``` took the 5 minutes, so removing the ```print(response.parsed)```  will fix it

**Comment by Bobspadger** [comment]
It Shouldn't take 5 minutes to parse the xml -thats crazy!?!? What are you running this on?

**Comment by Xbeninni** [comment]
@Bobspadger  I was running this from git bash on windows 10

**Comment by Bobspadger** [comment]
@Xbeninni try running it just from idle and not via the git bash environment.

Or just from the command line - that performance sounded terrible!

**Comment by Xbeninni** [comment]
@Bobspadger  right, I switched to command prompt. Thank you all, I appreciate your help. Stay safe!
