### ISSUE TITLE
cant get order status attribute to work

### ISSUE THREAD

**Issue by rick0403** [python-amazon-mws/python-amazon-mws#174]
Great library! ... the door to Amazon MWS is creaking open!
This works for me, supplying the 'created_after' parameter:
orders = orders_api.list_orders(marketplaceids=[marketplace_usa], created_after='2020-04-23')

I want to request only unshipped orders, which works fine in the scratchpad:
 &OrderStatus.Status.1=Unshipped
I see in the mws api file orders.py there is a order_statuses parameter, but when I try to sneak it in like this:
orders = orders_api.list_orders(marketplaceids=[marketplace_usa], created_after='2020-04-23', order_statuses='Unshipped')

I get the error:
Traceback (most recent call last):
  File "getMWSorders.py", line 15, in <module>
    orders = orders_api.list_orders(marketplaceids=[marketplace_usa], created_after='2020-04-23', order_statuses='Unshipped')
  File "C:\Users\rdmos\Miniconda3\lib\site-packages\mws\utils.py", line 250, in _wrapped_func
    return request_func(self, *args, **kwargs)
TypeError: list_orders() got an unexpected keyword argument 'order_statuses'

How can I request only 'Unshipped" orders?

**Comment by GriceTurrble** [comment]
The argument names for that method have changed from 0.x (master branch, on PyPI currently) to 1.x (develop branch, WIP).

In the older version, the arg name is `orderstatus`:

https://github.com/python-amazon-mws/python-amazon-mws/blob/f80892158070d1edcb94beb5dc39df07cb8b728e/mws/mws.py#L531-L534

**Comment by rick0403** [comment]
That's it! Thank you!  I am new to github, and very new to downloading source code to see if I can figure out how to use a new package if there's not much documentation. I installed 0.x from Pypl; I guess I downloaded the 1.x version from github to poke around. It would have taken me forever to spot this, thank you.
Would you recommend running the Dev version instead? I'm a one-man band trying to automate things for my own shop; I would trade more functionality for a little uncertainty / instability.

**Comment by GriceTurrble** [comment]
For the time being, yes, the 1.x dev version is relatively safe to use. However, it is bound to be updated and broken in the near term, with function signatures changing, classes being moved to different modules, etc.
