### ISSUE TITLE
General help on mws xsd -> xml feeds

### ISSUE THREAD

**Issue by btcorgtfo** [python-amazon-mws/python-amazon-mws#175]
hi!,
first, thanks for the contributions and all your replies here :-) Helped me a lot to get started with some mws helper functions.

however, i am stuck in dealing with mws feeds, especially using xsd/xml instead of flat files.

I updated my listing on amazon now for a while with flatfile (.tsv) upload which worked fine. However I now want to switch to xml for changing price etc. 

I have read some docu, some posts but i am still _mentally_ stuck on how to even utilize the xsd provided by amazon on their mws docu page (http://docs.developer.amazonservices.com/en_DE/feeds/Feeds_FeedType.html)

maybe some of you can drop me a few hints how to move on?

1. Do I need to construct the whole xml myself locally (including header, `envelope.xsd` files etc in the same directory), right? One would load `Price.xsd` for price changes, and e.g.` ProductImage.xsd `for image changes?

2. which workflow can you suggest, at the moment i try:

load xsd (e.g. `Price.xsd`) via `xmlschema.XMLSchema(...)` and try to set values via 
`xml = xmlschema.from_json(jsonobject, xmlschema)` but here i am stuck. I have no idea how to format the json or even know which values to set.

```
xsd = xmlschema.XMLSchema('./application/static/xsd/amzn-header.xsd')
data = ({'SKU': '9876543210'})
jsondata = json.dumps(data)
xml = xmlschema.from_json(jsondata, schema=xsd)

```
is there a way to construct a json from xsd / know which fields are needed, because
here was posted a short price xml, but the `Price.xsd `file is much longer (https://github.com/python-amazon-mws/python-amazon-mws/issues/157#issuecomment-594018507)
also for example i dont see the `MerchantID `header anywhere in the `Price.xsd `file (also not in the inclued `amzn-base.xsd`)

any small help would be highly appreciated :o)

**Comment by elcolumbio** [comment]
You actually have an interesting approach, when it comes to load xsd and use that in your code.
But that is adding a whole lot of complexity only to get started.
I would recommend you to get started with the most simple example. Maybe change something you find here slightly.
I found an example in one of my older projects: https://github.com/elcolumbio/mlrepricer/blob/5b3c49c7ab6770239f2cd007d002321613217140/mlrepricer/updateprice.py#L131-L143

That is the payload you can pass into this sdk, you see how i do it under the cited code.

**Comment by fullstackadam** [comment]
> also for example i dont see the `MerchantID `header anywhere in the `Price.xsd `file (also not in the inclued `amzn-base.xsd`)

You can check amzn-header.xsd for `MerchantIdentifier`

https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/amzn-header.xsd
