### ISSUE TITLE
ReportOptions in request_report

### ISSUE THREAD

**Issue by deathdropsk8** [python-amazon-mws/python-amazon-mws#178]
So there  currently isnt a way I can see to request a custom report in the request_report function. In my personal instance I am downloading a '_GET_MERCHANT_LISTINGS_ALL_DATA_' and need to add in 'ReportOptions=custom%3Dtrue' to the HTTP GET request. There is currently no way to do it in the current library. Request specifics can be found at the below like from Amazon https://docs.developer.amazonservices.com/en_UK/reports/Reports_ReportType.html

**Comment by GriceTurrble** [comment]
Thank you for the report! See PR #180 for changes that should correct for this.

I do not have a seller account with which to test, but the change is relatively small, so I am 90% confident in the change written. Feel free to pull those changes and prove me wrong, though. :)

Note this change was made against our `develop` branch, which is a development version that will eventually become a 1.0 release. There are some differences between that version and the 0.8.x version out on PyPI (that one matches our `master` branch).

If you are using the PyPI version, changing over to our dev version will have some backwards-incompatible changes. Let us know here or in our Slack \#help channel if you need assistance.
