### ISSUE TITLE
How to add prepdetails list item when creating inbound shipment

### ISSUE THREAD

**Issue by lswamy** [python-amazon-mws/python-amazon-mws#179]
When creating an inbound shipment plan, how do I add PrepDetails ?

https://docs.developer.amazonservices.com/en_US/fba_inbound/FBAInbound_Datatypes.html#InboundShipmentPlanRequestItem

I looked at the the source code in inbound_shipments.py and there is no reference to this parameter. We would like to set the PropOwner property when creating shipments

For example the request items would be like this:

`&InboundShipmentPlanRequestItems.member.1.SellerSKU=SKU00001
&InboundShipmentPlanRequestItems.member.1.Quantity=1
&InboundShipmentPlanRequestItems.member.1.PrepDetailsList.member.1.PrepInstruction=Taping
&InboundShipmentPlanRequestItems.member.1.PrepDetailsList.member.1.PrepOwner=AMAZON`

**Comment by Bobspadger** [comment]
Looking at `create_inbound_shipment_plan(self, items, country_code='US', subdivision_code='', label_preference='')` https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/apis/inbound_shipments.py#L192

and

https://docs.developer.amazonservices.com/en_US/fba_inbound/FBAInbound_CreateInboundShipment.html

so the `items` argument relates to `InboundShipmentItems`

This then passes items through the `parse_item_args` function which checks that required keys are in place, or throws an error.

`PrepDetailsList` is not a required argument, so should be able to be added to this dictionary

I've not tried this, and I'm using the dev branch for reference here.

**Comment by GriceTurrble** [comment]
Definitely some room for improvement here. `parse_item_args` was an early attempt to handle this with some special dictionary conversion, but it is cannot currently handle `PrepDetailsList`; and adding that to the existing code would be cumbersome.

This needs some new architecture, I think. Some native objects like a `PrepDetail` class and an `Item` class (or two separate classes for `InboundShipmentPlanRequestItem` and `InboundShipmentPlanItem`) that can contain multiple `PrepDetails` in a list, and each should be able to serialize itself into the appropriate parameter.

I'll spend some time on this in the near term.
