### ISSUE TITLE
Start adding deprecation warnings to master branch methods

### ISSUE THREAD

**Issue by GriceTurrble** [python-amazon-mws/python-amazon-mws#183]
A number of method signatures in the `develop` branch are different compared to their `master` branch counterparts. This has significance in two ways:

1. Our current version on PyPI is based on `master` branch, but our default branch here is `develop`. When users install from PyPI and later view our source code, they will see different information from what their installed version includes, and may (and have on some occasions) use the incorrect method arguments.
2. When we do eventually release our `develop` branch as a 1.x version on PyPI, the breaking changes will cause some users - especially those who install or update the package via some automated method and/or without pinning the version - to have breaks in their own programs.

Moving forward, we should implement deprecation warnings into our `master` branch code that warns our end users of the upcoming changes. That will allow them to continue using the 0.8.x version (with patch updates not breaking backwards compatibility) while having adequate warnings for upcoming changes to develop branch, so that they can make adjustments in their own time.

**Comment by Bobspadger** [comment]
Agreed, also, that python3.4 and below will no longer be supported.

**Comment by GriceTurrble** [comment]
Some deprecations added for merge to `develop` in #207 . Will backport some in a minor release to `master` in near future.
