### ISSUE TITLE
How to use OutboundShipments?

### ISSUE THREAD

**Issue by 854350999** [python-amazon-mws/python-amazon-mws#185]
like Ttile

**Comment by Bobspadger** [comment]
We just create an interface for connecting to amazon - if you refer to their docs, you should see we just provide a way to deal with their requested inputs:

http://docs.developer.amazonservices.com/en_UK/fba_outbound/FBAOutbound_Overview.html

**Comment by 854350999** [comment]
Thanks for the reply, I have read this reference document, but when I call the API of ListAllFulfillmentOrders, it does not return information to me, and the QueryStartDateTime parameter that should appear when i use your code, but it does not appear.
hopes the new reply.

**Comment by Bobspadger** [comment]
looks like that call has not been implemented yet:

```python
    @next_token_action('ListAllFulfillmentOrders')
    def list_all_fulfillment_orders(self, next_token=None):
        """
        Returns a list of fulfillment orders fulfilled after (or at) a specified date.
        Pass `next_token` to call "ListAllFulfillmentOrdersByNextToken" instead
        Docs:
        http://docs.developer.amazonservices.com/en_US/fba_outbound/FBAOutbound_ListAllFulfillmentOrders.html
        """
        raise NotImplementedError
```
https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/apis/outbound_shipments.py#L110-L120

Shouldn't be  too hard to do if you fancy submitting a pull request?

**Comment by 854350999** [comment]
How do I enter (specified date) this parameter into this code.
```python
import mws

order = mws.OutboundShipments(account_id='A20J3ITGxxxxx', access_key='xxxxxxxxxxxx',
                              secret_key='xxxxxxxxxxxxxxx')


res = order.list_all_fulfillment_orders()
print(res.response.text)
```
where QueryStartDateTime this parameter should be filled.

**Comment by Bobspadger** [comment]
Closing as has been fixed in  PR referenced above.
