### ISSUE TITLE
Can't find the "Business Reports" API

### ISSUE THREAD

**Issue by Jared66** [python-amazon-mws/python-amazon-mws#186]
I can obtain the "**Unit Session Percentage**" from the  report "**Detail Page Sales and Traffic by Child Item**" of "**Business Reports**"  (see the attached picture) to know how many pepole visited my product details page and how many items they bought for a product.

But I can't find any APIs to get that data :
https://docs.developer.amazonservices.com/en_UK/reports/Reports_ReportType.html

![Business Reports](https://user-images.githubusercontent.com/63780946/87222330-6df4c780-c3a5-11ea-9806-2b0856e069fc.png)

**Comment by saleweaver** [comment]
There's no such report available through amazon mws. The closest you can get is the advertising api, but you have to register an account as an advertising developer which is quite difficult to get.

**Comment by Jared66** [comment]
> There's no such report available through amazon mws. The closest you can get is the advertising api, but you have to register an account as an advertising developer which is quite difficult to get.

thanks

**Comment by Jared66** [comment]
solved
