### ISSUE TITLE
Dictwrapper xml decode exception

### ISSUE THREAD

**Issue by Bobspadger** [python-amazon-mws/python-amazon-mws#188]
Reported that there are sometimes Unicode decode errors reported at the .decode()

Might be worth handling this error and returning mwseception with the response attached so that it can be decoded by the user correctly, along with providing better and easier troubleshooting

**Comment by 854350999** [comment]
Is there a code example here? I encountered this error but I don’t know how to solve it

> 报告有时在.decode（）处报告Unicode解码错误
> 
> 可能值得处理此错误并返回带有附加响应的mwseception，以便用户可以正确对其进行解码，并提供更好，更轻松的故障排除

Is there a code example here? I encountered this error but I don’t know how to solve it

**Comment by 854350999** [comment]
> Reported that there are sometimes Unicode decode errors reported at the .decode()
> 
> Might be worth handling this error and returning mwseception with the response attached so that it can be decoded by the user correctly, along with providing better and easier troubleshooting

Is there a code example here? I encountered this error but I don’t know how to solve it

**Comment by 854350999** [comment]
I have solved it, you should modify TypeError to UnicodeDecodeError in mws.py file, and then you can successfully parse the report in csv format.

**Comment by 854350999** [comment]
But I still don’t know how to parse the report obtained in this way
