### ISSUE TITLE
can't get report of some report type

### ISSUE THREAD

**Issue by Jared66** [python-amazon-mws/python-amazon-mws#190]
I can get the report data whose type is `_GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_`, but I can't get the report of `_GET_FLAT_FILE_ORDERS_DATA_`

See the attached picture to get more details.

In fact, I just want to know the sales volume of each SKU in every day. But I find that the data from `_GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_` is very inaccurate. Does anyone have a better method to achieve my purpose ?

![_GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_](https://user-images.githubusercontent.com/63780946/87667785-86962080-c79d-11ea-9ef2-e334a2842f9f.png)

![_GET_FLAT_FILE_ORDERS_DATA_](https://user-images.githubusercontent.com/63780946/87667804-8f86f200-c79d-11ea-8d64-405aa30b565d.png)

**Comment by Bobspadger** [comment]
Can you look in the `response` object, and look for the `request` , in there should be the untouched response from Amazon

Can you check if its a valid XML file, or if there is some more info from Amaozn.

I can see you are using Pycharm so should be a doddle to do!

**Comment by Jared66** [comment]
> Can you look in the `response` object, and look for the `request` , in there should be the untouched response from Amazon
> 
> Can you check if its a valid XML file, or if there is some more info from Amaozn.
> 
> I can see you are using Pycharm so should be a doddle to do!

Thanks for your rapid reply.

![resp](https://user-images.githubusercontent.com/63780946/87670196-eee70100-c7a1-11ea-8cd9-f1ea55e47f8e.png)

![resp](https://user-images.githubusercontent.com/63780946/87669719-0f628b80-c7a1-11ea-8e25-e1118077eadd.png)

![r2](https://user-images.githubusercontent.com/63780946/87670232-fe664a00-c7a1-11ea-82cc-2a36e60132c4.png)

**Comment by Bobspadger** [comment]
So on the face of it, the our code is working as expected, Amazon have not returned you any useable data

however, have you seen https://docs.developer.amazonservices.com/en_UK/reports/Reports_Overview.html

Where they show you the flow is:

RequestReport (`request_report`) -> returns `ReportRequestId`
GetReportList (`get_report_request_list` / `get_report_list`) -> Checks to see what is ready, this gives you the `GeneratedReportId`
GetReport (`get_report`) passing in the `GeneratedReportId or ReportId`


Its the final stage that returns the report, but only AFTER it is ready from amazon.

I often find these can take 15+minutes

**Comment by Jared66** [comment]
@Bobspadger 
Thank you very very much. 
I missed some steps, so I didn't know the status of the requests. In fact, I missed some parameters or set the parameters incorrectly when I request report of some types, which make me can't get the report  correctly. 
Through the `get_report_request_list` , I can know the mistake of my parameters. That help me a lot !!!

**Comment by Jared66** [comment]
@Bobspadger 
Thank you very very much. 
I missed some steps, so I didn't know the status of the requests. In fact, I missed some parameters or set the parameters incorrectly when I request report of some types, which make me can't get the report  correctly. 
Through the `get_report_request_list` , I can know the mistake of my parameters. That help me a lot !!!
