### ISSUE TITLE
NoneType error when submiting feed with no Marketplaceids

### ISSUE THREAD

**Issue by nuno407** [python-amazon-mws/python-amazon-mws#196]
HI 👋 ,

I would like to submit a bug report.

According to the docs in http://docs.developer.amazonservices.com/en_US/feeds/Feeds_SubmitFeed.html
the use of the query param is not required in the majority of the feeds (only for Product Images Feeds) therefore calls to the method submit_feeds from Feeds class should be able to coupe with it. It happens that, if no market place is provided , the library will crash in https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/utils.py#L154 saying `TypeError: 'NoneType' object is not iterable`. This bug seems to be caused by https://github.com/python-amazon-mws/python-amazon-mws/pull/124.

Regards,
Nuno

**Comment by GriceTurrble** [comment]
Awaiting change request in #193 which should be a fix for this issue.

Thank you for the report. 👍
