### ISSUE TITLE
Order Fulfillment feed -> Get Paid

### ISSUE THREAD

**Issue by mbolder** [python-amazon-mws/python-amazon-mws#204]
Hello,

I am trying now automate the process for orders that are send by us, so setting the carrier code and tracking number. Any advice or examples would be greatly appreciated, specially the case where an order is split in several packages.

**Comment by Bobspadger** [comment]
Are you referring to Merchant fulfilled prime?

This is where you purchase shipping via amazon?

If so, the tracking details are returned to you in the `create_shipment` call as `.parsed.Shipment.TrackingId`

If you are shipping the items via your own carrier, you can send Amazon the tracking reference via the `feeds` api

an example of this would be:

```
feeds_api = MWSFactory.factory('feeds')
    feed_headings = ['order-id', 'order-item-id', 'quantity', 'ship-date', 'carrier-code', 'carrier-name',
                     'tracking-number', 'ship-method']
    feed_header = '\t'.join(feed_headings)
    feed_header = '{}\n'.format(feed_header)
    feed_row_template = '{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}'
```

This gets an instance of the feeds api (via my own factory method) then builds a string of headings - including carrier details.

Then simply `.format` in the required data and join the created data to the header.

`result = feeds_api.submit_feed(feed_data, '_POST_FLAT_FILE_FULFILLMENT_DATA_')`

done.
