### ISSUE TITLE
How to upload PDF invoice?

### ISSUE THREAD

**Issue by Thutmose3** [python-amazon-mws/python-amazon-mws#208]
Hi,

I'm trying to upload a PDF invoice.
The submit feeds works, but i get this error:

"Feed Processing Summary: 
Number of records processed 1 
Number of records successful 0
79503 Error
**Invoice uploaded is not pdf for shipmentId** N/A, orderId 405-example-4561315 and InvoiceNumber 11-2020-2-1"

It seems that MWS does not accept my PDF, but when i check the Base64 string, it is correct.

This is my request code:

    feeds_api = mws.Feeds(region="UK")
    base64_invoice = base64.b64encode(pdf_invoice.read())
    response = feeds_api.submit_feed(
        feed=base64_invoice,
        feed_options={"OrderId": order_id, "InvoiceNumber": invoice_id},
        feed_type="_UPLOAD_VAT_INVOICE_",
        marketplaceids=["Example"]
    )

Am i doing something wrong with the base64?
Thanks for your help

**Comment by GriceTurrble** [comment]
The file is sent as bytes, not base64. Try `.read().encode('iso-8859-1')`.

**Comment by Thutmose3** [comment]
Great! It worked with just `pdf_invoice.read()` for me.

Thanks!

**Comment by rick0403** [comment]
ll l..4.

**Comment by rick0403** [comment]
.
