### ISSUE TITLE
Add report type enums

### ISSUE THREAD

**Issue by jameshiew** [python-amazon-mws/python-amazon-mws#21]
http://docs.developer.amazonservices.com/en_UK/reports/Reports_ReportType.html

**Comment by elcolumbio** [comment]
i found [this source ](https://github.com/caponica/AmazonMwsComplete/blob/master/src/CaponicaAmazonMwsComplete/ClientPack/MwsFeedAndReportClientPack.php)as quite helpful.

I did use something [like that](https://gist.github.com/elcolumbio/10664b8dff40dba7811039670e4b1b25). It's very bad, but for people from europe it seems to be important which encoding those reports have.

**Comment by elcolumbio** [comment]
i updated that gist. Shortened names, i think they still should be shorter.
Also now you can do this
``` python
AllReports.ACTIVE_LISTINGS.report
# returns '_GET_MERCHANT_LISTINGS_DATA_'

AllReports.ACTIVE_LISTINGS.encoding
# returns False
```
should rename encoding to isutf8

**Comment by GriceTurrble** [comment]
Enumerations added by #74 . Not currently used, but available. We'll explore what we can do with it shortly.
