### ISSUE TITLE
create_inbound_shipment_plan issues

### ISSUE THREAD

**Issue by cajohn2757** [python-amazon-mws/python-amazon-mws#217]
I am attempting to create an inbound shipment plan, but after running the script it without throwing errors the shipment plan does not appear in Amazons system.

```
from mws import InboundShipments
import mws

MWS_ACCESS_KEY='xxxx'
MWS_SECRET_KEY='xxxx'
MWS_ACCOUNT_ID='xxxx'
address={'name':'company_value','address_1':'address_1_value','city':'city_value','state_or_province':'state_code_value','postal_code':'postal_code_value'}
items=({'sku':'sku_value','quantity':1,'asin':'asin_value'},{'sku':'sku_value','quantity':2,'asin':'asin_value'})

inboundShipments = mws.InboundShipments(
    access_key=MWS_ACCESS_KEY,
    secret_key=MWS_SECRET_KEY,
    account_id=MWS_ACCOUNT_ID,
)

inboundShipments.set_ship_from_address(address)

inboundShipments.create_inbound_shipment_plan(items,label_preference='SELLER_LABEL')
```

I'm not sure if something is wrong or why the shipping plan is not appearing within Amazon.

**Comment by viavacavi** [comment]
I have been discussing this issue in #215 

I've made some progress today figuring stuff out, I'll post there soon

**Comment by GriceTurrble** [comment]
The response from `create_inbound_shipment_plan` will provide you with details on the shipments Amazon wants you to create. It is then up to you to parse those plans from the response and run `create_inbound_shipment` for each of those plans.

Those plans won't appear on Seller Central because those systems are separate: SC will show the plan details on the page only when making shipments within Seller Central, but I don't think it stores those plans in perpetuity. When performing the workflow in MWS, they expect you to handle everything in MWS exclusively.

---

So, you will need to capture the response from the request method:

```python
resp = inboundShipments.create_inbound_shipment_plan(items,label_preference='SELLER_LABEL')

for plan in resp.parsed.InboundShipmentPlans.member:
    # parse the plan details
```

You might see each plan take this form in XML (per Amazon's example in documentation):

```xml
<DestinationFulfillmentCenterId>ABE2</DestinationFulfillmentCenterId>
<LabelPrepType>SELLER_LABEL</LabelPrepType>
<ShipToAddress>
  <City>Breinigsville</City>
  <CountryCode>US</CountryCode>
  <PostalCode>18031</PostalCode>
  <Name>Amazon.com</Name>
  <AddressLine1>705 Boulder Drive</AddressLine1>
  <StateOrProvinceCode>PA</StateOrProvinceCode>
</ShipToAddress>
<EstimatedBoxContentsFee>
  <TotalUnits>10</TotalUnits>
  <FeePerUnit>
    <CurrencyCode>USD</CurrencyCode>
    <Value>0.10</Value>
  </FeePerUnit>
  <TotalFee>
    <CurrencyCode>USD</CurrencyCode>
    <Value>10.0</Value>
  </TotalFee>
</EstimatedBoxContentsFee>
<Items>
  <member>
    <FulfillmentNetworkSKU>FNSKU00001</FulfillmentNetworkSKU>
    <Quantity>1</Quantity>
    <SellerSKU>SKU00001</SellerSKU>
    <PrepDetailsList>
      <PrepDetails>
        <PrepInstruction>Taping</PrepInstruction>
        <PrepOwner>AMAZON</PrepOwner>
      </PrepDetails>
    </PrepDetailsList>
  </member>
</Items>
<ShipmentId>FBA0000001</ShipmentId>
```

... so for each `plan` you might use data like:

```python
for plan in resp.parsed.InboundShipmentPlans.member:
    print(plan.ShipmentId)
    print(plan.LabelPrepType)
    for item in plan.Items.member:
        print(item.FulfillmentNetworkSKU)
        print(item.SellerSKU)
        print(item.Quantity)
```

And then you'll want to use `create_inbound_shipment` for each of `plan`, supplying the ShipmentId, DestinationFulfillmentCenterId, items, prep details, etc.

**Comment by cajohn2757** [comment]
When creating the inbound shipment the following error is thrown:

```<Message>Error: You must include a valid ShipmentId with a call to the CreateInboundShipment operation. Get ShipmentId values by calling the CreateInboundShipmentPlan operation. The request to CreateInboundShipment must include only items and quantities that have been previously planned through CreateInboundShipmentPlan. If a ShipmentId is not used to create a shipment within 48 hours it will expire.</Message>```

Can someone please help? I have read that this is because ```create-inbound-shipment``` uses ```QuantityShipped``` and not ```Quantity```. is this correct?

**Comment by GriceTurrble** [comment]
Using the method signature as a reference:

https://github.com/python-amazon-mws/python-amazon-mws/blob/0d93238e0c3ece9533e8a0eb31f0108c918f26ae/mws/apis/inbound_shipments.py#L234-L244

A few potential issues here:

1. `shipment_id` should be the same as the `ShipmentId` key you received from a successful response from `create_inbound_shipment_plan`. If that doesn't match, they will likely deny it.
2. `destination` should match the `DestinationFulfillmentCenterId` key from that same plan response.
3. `items` is a list of item dictionaries similar to the ones sent to `create_inbound_shipment_plan`, though only "sku" and "quantity" keys are required unless you're using case packs.
    - We map these keys to the correct request parameters using the function [`parse_item_args`](https://github.com/python-amazon-mws/python-amazon-mws/blob/0d93238e0c3ece9533e8a0eb31f0108c918f26ae/mws/apis/inbound_shipments.py#L14). Except in some extreme case, the request parameters *should* be correct.
     - Note that Amazon may request you split quantities and ship to multiple FCs in one plan, so you must inspect the `Items` for each plan first. If you specify a quantity to be shipped to an FC that was not planned for, that might be the cause of your error.
4. `shipment_status` very likely you want `"WORKING"` for in-progress shipments or `"SHIPPED"` for those already given to a carrier.
5. `label_preference` would likely be the same as the `label_preference` given to `create_inbound_shipment_plan`.

Based on this, MWS is indicating either the `shipment_id` is incorrect or expired, or that the planned items are not in correct quantities for the planned destinations.

**Comment by cajohn2757** [comment]
When parsing the ```create_inbound_shipment_plan``` as you described, it returns multiple shipments. 

Code:
```resp = inboundShipmentPlan.create_inbound_shipment_plan(items, label_preference='SELLER_LABEL')

for plan in resp.parsed.InboundShipmentPlans.member:
    print(plan.ShipmentId)
    print(plan.LabelPrepType)
    for item in plan.Items.member:
        print(item.FulfillmentNetworkSKU)
        print(item.SellerSKU)
        print(item.Quantity)```

Output:
```
#hidden out for privacy
FBA15S1PL19C
NO_LABEL
B07Y8*****
85000*****
64
B075J*****
85940*****
60
FBA15S1QPF95
NO_LABEL
B07Y8*****
85000*****
26
B075J*****
85940*****
30

Process finished with exit code 0```

First, I'm confused how the ```label_preference``` is ```NO_LABEL``` when I specified ```SELLER_LABEL``` 

Second, Since it is splitting the Shipment plan into multiple shipments will I have to re-adjust the quantity before creating the shipment?

**Comment by cajohn2757** [comment]
```
inboundShipmentPlan.create_inbound_shipment(shipment_id=plan.ShipmentId,shipment_name='Trial',
                                                   destination=plan.DestinationFulfillmentCenterId, items=items, label_preference='SELLER_LABEL')
```
This is the code within the ```item``` nested for loop that throws the error.

**Comment by GriceTurrble** [comment]
The plan returns a set of InboundShipmentPlan objects in XML, detailed here: https://docs.developer.amazonservices.com/en_US/fba_inbound/FBAInbound_Datatypes.html#InboundShipmentPlan

The `LabelPrepType` in the response indicates the requirement for that plan. This one I had wrong, actually: a value of `NO_LABEL` indicates Amazon can accept the items as stickerless co-mingled (i.e. they can use UPC or other barcodes already on products to identify them). Otherwise they require `SELLER_LABEL` (you apply labels) or `AMAZON_LABEL` (they will process your items at the FC and apply their own labels, part of a paid service they offer).

So you'll want to provide the `LabelPrepType` they specify in the plan response for the `label_preference` in your `create_inbound_shipment` call.

---

As for `items`, be certain it contains only the quantities specified in the plan, not the ones you originally requested. Your code should look similar to:

```python

```

Then you should be able to send it as:

```python
for plan in resp.parsed.InboundShipmentPlans.member:
    shipment_items = []  # avoiding the `items` name, likely used elsewhere already
    for item in plan.Items.member:
        shipment_items.append({
            'sku': item.SellerSKU,
            'quantity': item.Quantity,
        })

    created_resp = inboundShipmentPlan.create_inbound_shipment(
        shipment_id=plan.ShipmentId,
        destination=plan.DestinationFulfillmentCenterId,
        items=shipment_items,
        label_preference=plan.LabelPrepType,
    )
    print(f"Shipment {created_resp.parsed.ShipmentId} created!")
```

(while the argument name `label_preference` might be a poor name choice, MWS's request param for that data is `LabelPrepPreference`, so 🤷 )

**Comment by cajohn2757** [comment]
Thank you so much! It is now working!

**Comment by cajohn2757** [comment]
@GriceTurrble When trying to run the script today, it is acting as if the response from ```create_inbound_shipment_plan``` does not have certain attributes. 
```AttributeError: 'str' object has no attribute 'ShipmentId'```

**Comment by GriceTurrble** [comment]
Can you output the response you're getting entirely, to see what's in there?

**Comment by cajohn2757** [comment]
When running ```print(resp.parsed.InboundShipmentPlans.member)``` it prints
```{'value': '\n        ', 'LabelPrepType': {'value': 'SELLER_LABEL'}, 'DestinationFulfillmentCenterId': {'value': 'CLT2'}, 'ShipToAddress': {'value': '\n          ', 'City': {'value': 'Charlotte'}, 'CountryCode': {'value': 'US'}, 'PostalCode': {'value': '28214-8082'}, 'Name': {'value': 'Amazon.com Services, Inc.'}, 'AddressLine1': {'value': '10240 Old Dowd Rd'}, 'StateOrProvinceCode': {'value': 'NC'}}, 'ShipmentId': {'value': 'FBA15SBWMJZY'}, 'EstimatedBoxContentsFee': {'value': '\n          ', 'TotalFee': {'value': '\n            ', 'CurrencyCode': {'value': 'USD'}, 'Value': {'value': '5.00'}}, 'FeePerUnit': {'value': '\n            ', 'CurrencyCode': {'value': 'USD'}, 'Value': {'value': '0.10'}}, 'TotalUnits': {'value': '50'}}, 'Items': {'value': '\n          ', 'member': {'value': '\n            ', 'Quantity': {'value': '50'}, 'FulfillmentNetworkSKU': {'value': '***'}, 'SellerSKU': {'value': '*8***'}}}}```
