### ISSUE TITLE
AttributeError: 'str' object has no attribute 'ProductCategoryId'

### ISSUE THREAD

**Issue by azmanomer** [python-amazon-mws/python-amazon-mws#226]
Hello i tried lots of things but i couldnt manage to reach attributes :( i'm trying with this code;

```
from mws import mws
access_key = 'xxxxx'#replace with your access key
seller_id = 'xxxxx'#replace with your seller id
secret_key = 'xxxxxx'#replace with your secret key
marketplace_usa = 'ATVPDKIKX0DER'

products_api = mws.Products(access_key, secret_key, seller_id, region='US')
products = products_api.get_product_categories_for_asin(marketplaceid=marketplace_usa, asin='B086DPR1G2')
print(products.parsed)
for self_category in products.parsed:
    print(self_category.ProductCategoryId, self_category.ProductCategoryName)
```

product.parsed return "{'Self': {'ProductCategoryId': {'value': '3422301'}, 'ProductCategoryName': {'value': 'Mats'}, 'Parent': {'ProductCategoryId': {'value': '3422251'}, 'ProductCategoryName': {'value': 'Yoga'}, 'Parent': {'ProductCategoryId': {'value': '3407731'}, 'ProductCategoryName': {'value': 'Exercise & Fitness'}, 'Parent': {'ProductCategoryId': {'value': '10971181011'}, 'ProductCategoryName': {'value': 'Sports & Fitness'}, 'Parent': {'ProductCategoryId': {'value': '3375301'}, 'ProductCategoryName': {'value': 'Categories'}, 'Parent': {'ProductCategoryId': {'value': '3375251'}, 'ProductCategoryName': {'value': 'Sports & Outdoors'}}}}}}}}" it has ProductCategoryId but it still give me error AttributeError: 'str' object has no attribute 'ProductCategoryId'

**Comment by GriceTurrble** [comment]
This was a known issue in `develop` version until we implemented native iteration for the dict-like object returned by `.parsed`. Checking back now on the `master` version, those changes have not been backported.

Will push that into next patch version for 0.8 branch. Thank you!

**Comment by azmanomer** [comment]
Thank you for the fast answer. I tried with new commit but this time i getting following error;
```
Traceback (most recent call last):
  File "new_3.py", line 35, in <module>
    print(self_category.ProductCategoryId, self_category.ProductCategoryName)
  File "C:\Users\omero\anaconda3\lib\site-packages\mws\utils.py", line 33, in __getattr__
    return self.__getitem__(item)
  File "C:\Users\omero\anaconda3\lib\site-packages\mws\utils.py", line 49, in __getitem__
    node = super().__getitem__(key)
KeyError: 'ProductCategoryId'
```
Btw im noob with python so if its because of my lack of knowladge im sorry in advance.

**Comment by GriceTurrble** [comment]
This one is to be expected. The node's initial key is `"Self"`, so there is no `"ProductCategoryId"` at that node level.

You can adjust that by using `for self_category in products.parsed.Self:` to get to that first node, but the way that particular response is laid out, you'll find that there aren't many categories to loop over without designing for some recursive call that looks into the `"Parent"` keys.

Per your example:

```python
{
    "Self": {
        "ProductCategoryId": {"value": "3422301"},
        "ProductCategoryName": {"value": "Mats"},
        "Parent": {
            "ProductCategoryId": {"value": "3422251"},
            "ProductCategoryName": {"value": "Yoga"},
            "Parent": {
                "ProductCategoryId": {"value": "3407731"},
                "ProductCategoryName": {"value": "Exercise & Fitness"},
                "Parent": {
                    "ProductCategoryId": {"value": "10971181011"},
                    "ProductCategoryName": {"value": "Sports & Fitness"},
                    "Parent": {
                        "ProductCategoryId": {"value": "3375301"},
                        "ProductCategoryName": {"value": "Categories"},
                        "Parent": {
                            "ProductCategoryId": {"value": "3375251"},
                            "ProductCategoryName": {"value": "Sports & Outdoors"},
                        },
                    },
                },
            },
        },
    }
}
```

Iterating on `Self` will only return the "Mats" category. To get to the innermost one, `"Sports & Outdoors"`, you would need something like `products.parsed.Parent.Parent.Parent.Parent.Parent.ProductCategoryName`.

**Comment by azmanomer** [comment]
:) Thank you for explanation it is really make things easier to understand

**Comment by GriceTurrble** [comment]
Keys are case-sensitive, I'm afraid. You'll need to use `"Self"`, not `"self"`.

**Comment by azmanomer** [comment]
Thank you :)
