### ISSUE TITLE
_ssl.c:877

### ISSUE THREAD

**Issue by 2445809596** [python-amazon-mws/python-amazon-mws#230]
### I have this problem
```EOF occurred in violation of protocol (_ssl.c:877) ```

**Comment by Bobspadger** [comment]
Could we get a bit more details please?

What API call are you trying to do?

That looks very much like you may have a broken SSL module / setup - I've had similar where python / system encryption modules were a bit broken!

**Comment by GriceTurrble** [comment]
Not sure this is in scope. Do you have more details on what caused this error for you, such as the Python version you're using, your environment, version of python-amazon-mws you have installed, etc.?

**Comment by 2445809596** [comment]
I encountered this problem when I called the feedapi

python： 3.6.8

python-amazon-mws：0.8.10

I have encountered this problem before. I don't know why it's suddenly good

But now it's happening again

**Comment by GriceTurrble** [comment]
Searching for similar errors related to `_ssl.c`, this is almost guaranteed to be some issue in your local setup, I'm afraid. And we would still need more detail to know why it is occurring for you, however.

For our part, we only touch SSL using the `requests` library by sending requests to MWS's endpoints, which are HTTPS. `python-amazon-mws` does nothing with SSL on its own.

For troubleshooting purposes, again, can you provide more details on your system setup, perhaps how you're utilizing `python-amazon-mws` in your own code? Is it CPython, which OS are you on, are you using `python-amazon-mws` in multi-threading, anything of that nature?

**Comment by 2445809596** [comment]
##### Thanks for the answer. I think I know what the problem is
I tested the following with windows 10 and centos7
```
import mws

access_key = "AKxxxxx"
secret_key = "xxxxx"
account_id = "xxxxx"
auth_token = "xxxxx"
region = "ES"
feed_api = mws.Feeds(access_key=access_key, secret_key=secret_key, account_id=account_id,
                          auth_token=auth_token, region=region)

res = feed_api.get_feed_submission_list(feedids=["5043xxxxx"])
```
There are no errors on Windows 10, and the error rate of centos7 is 50%
So I guess there's something wrong with my environment

**Comment by Bobspadger** [comment]
sounds like something up with the SSL library on centos.

I know centos uses redhats implementation and is sometimes horribly behind. I've had to patch this for PHP curl requests on magento before.

I can't remember the exact info behind it now though
