### ISSUE TITLE
Selling Partner API

### ISSUE THREAD

**Issue by jugi92** [python-amazon-mws/python-amazon-mws#234]
Will this library support the new Selling Partner API? For newly created Amazon accounts there is only the new [SP API](https://github.com/amzn/selling-partner-api-docs) and not MWS any longer. The new API seems to support the same functionality as MWS but still some changes in this library would be necessary to migrate projects based on this library to the new API.

**Comment by GriceTurrble** [comment]
This specific library, no. Enough things are different between MWS and SP-API that supporting both in the same code would be cumbersome.

I have plans to work on an SP-API client, though.

**Comment by jugi92** [comment]
Ok thanks for the update, it would be cool if you can let us know once you start with the new one. Cheers

**Comment by GriceTurrble** [comment]
Well, the space is set: https://github.com/python-amazon-mws/python-amazon-spapi

And if anyone feels like beating me to the punch :) , check out Amazon's Swagger/OpenAPI models: https://github.com/amzn/selling-partner-api-models
