### ISSUE TITLE
How install  dev14 of mws?

### ISSUE THREAD

**Issue by wdschn** [python-amazon-mws/python-amazon-mws#236]
I installed'dev14' from the master branch during development, but now I need to deploy it on another server to use it. When I installed from the master branch, it was updated to'dev15'. I am a newbie to github, I don’t Know how to install'dev14', can anyone help me?

**Comment by wdschn** [comment]
I modify the code and set _use_feature_mwsresponse = True to make it run under dev15, and at the same time modify all responses to MWSResponse. It's runing

**Comment by Bobspadger** [comment]
something like doing `git log` on the current install you have to see which commit you are working up to.

Then do an install with pip from git at that commit

```
pip install git+git://https://github.com/python-amazon-mws/python-amazon-mws.git@fac369b6ac83e208047a9a95608564344f79bbbb
```
and you should have the same working version.

**Comment by wdschn** [comment]
> something like doing `git log` on the current install you have to see which commit you are working up to.
> 
> Then do an install with pip from git at that commit
> 
> ```
> pip install git+git://https://github.com/python-amazon-mws/python-amazon-mws.git@fac369b6ac83e208047a9a95608564344f79bbbb
> ```
> 
> and you should have the same working version.

Thank you very much for your answer
