### ISSUE TITLE
ReportTypesEnums

### ISSUE THREAD

**Issue by yberezkin** [python-amazon-mws/python-amazon-mws#237]
Hello team,

First of all - wonderful job you do here. Thank you. Been using this report for a while.

I have a question, why the ReportType Enum is incomplete in mws/apis/reports.py
Is there a reason behind it? for instance "_GET_MERCHANT_LISTINGS_ALL_DATA_" which gives All Data Listing Report. or '_GET_MERCHANT_LISTINGS_INACTIVE_DATA_'

Is there an issue to add them in dev branch which I am not aware of? 

Thank you.

**Comment by GriceTurrble** [comment]
There hasn't been scrutiny on updating that enumeration, I gather. You are welcome to make a PR to add those in, of course.

Additionally, the string value for `report_type` can be passed manually to `Reports.request_report` and other operations. The enum is there for convenience.
