### ISSUE TITLE
Mocking MWS calls with pytest

### ISSUE THREAD

**Issue by Mitalee** [python-amazon-mws/python-amazon-mws#238]
Hi guys,

I've started to write test cases and was wondering if any of you have set up a test suite with pytest that mocks the network calls to Amazon MWS API. 

I'm currently looking at pytest-mock. Would appreciate any suggestions!

Regards,
Mitalee

**Comment by Bobspadger** [comment]
Have a look at all the hard work @GriceTurrble  has done in the test module:

Here's a good place to start: https://github.com/python-amazon-mws/python-amazon-mws/blob/9591d4059fd292faf18de834700a4776bfe6121f/tests/conftest.py#L135

**Comment by Mitalee** [comment]
@Bobspadger This is exactly what I needed after a full day of trying to make things work! Thank you and thank you @GriceTurrble!
