### ISSUE TITLE
module 'mws' has no attribute 'OutboundShipments'

### ISSUE THREAD

**Issue by Abdo99ab** [python-amazon-mws/python-amazon-mws#239]
Hello team,

Whenever I want to call the class OutboundShipments, I don't find it, I am getting this error:
AttributeError: module 'mws' has no attribute 'OutboundShipments'

Even though all of the others classes work fine (at least what I tested) including Orders, Feeds, Products, InboundShipments.

Is this from my side or is it a bug?

```
import mws
outbound = mws.OutboundShipments(region='MY_REGION', access_key='my_access_key', secret_key='my_secret_key', account_id='my_account_id')
```

**Comment by GriceTurrble** [comment]
Can you confirm which version of the package you are using, please?

**Comment by Abdo99ab** [comment]
Yes, I am using the version 0.8.10, which I think it's the latest as you're mentioning.

**Comment by Bobspadger** [comment]
https://github.com/python-amazon-mws/python-amazon-mws/blob/master/mws/mws.py#L1346

on the pypi release (0.8.10) there is no implementation of outbound shipments.


There are however implementations on the develop branch:

https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/apis/outbound_shipments.py


There is a todo there of `# TODO: Complete these methods` so might need @GriceTurrble  to see if he has completed them?

**Comment by Abdo99ab** [comment]
Thank you, dev branch, worked for me.
Waiting for it to be on the master branch.
