### ISSUE TITLE
About request report limit issue

### ISSUE THREAD

**Issue by 854350999** [python-amazon-mws/python-amazon-mws#245]
I tried to ```request a report``` from the European station one country by country, but when the request goes to the second country, the system will ```cancel``` my report. I have some reason to request this report ```one country by country```.And my ```request interval``` has reached 5 minutes. The official document only gives a ```one-minute limit```, I don’t know why

**Comment by GriceTurrble** [comment]
Apologies, I don't know how I can help with that one, as it appears to be limits particular to MWS.

Perhaps try the MWS support options listed [here](https://developer.amazonservices.com/support)?

**Comment by 854350999** [comment]
I'm very sorry to raise such a business question here, because I seem to be requesting compliance but it will be cancelled. I am wondering if it is because of my code problem that caused this result, but the result pointed out that this is not the case.Because I This result will also be available in its official scratchpad. Thank you very much for answering this question.
