### ISSUE TITLE
ReportOptions bug in develop. PR for v0.8.x?

### ISSUE THREAD

**Issue by Mitalee** [python-amazon-mws/python-amazon-mws#246]
Hi,

- As documented [here](https://github.com/python-amazon-mws/python-amazon-mws/pull/180#issuecomment-739950619), we have a critical requirement for ReportOptions, however we are unable to use v1.0.dev15 in the `develop` branch. 

- We are currently using v0.8.3 and I'm afraid a lot of functionality would also break if we move to v1.0.dev15. We would also like to move to SP-API and refactor as necessary at that point.

- For now we have made this work in v0.8.3 by going into site-packages and essentially modifying the code to the following, based on @GriceTurrble's PR #180 :

```python
def request_report(self, report_type, start_date=None, end_date=None, marketplaceids=(), report_options=None):
    #report_options = report_options or {}
    data = dict(Action='RequestReport',
                ReportType=report_type,
                StartDate=start_date,
                EndDate=end_date,
                ReportOptions=report_options)
    data.update(utils.enumerate_param('MarketplaceIdList.Id.', marketplaceids))
    return self.make_request(data)
```
- We are calling this using the following:
`requestid = reports_api.request_report(report_type="_GET_MERCHANT_LISTINGS_ALL_DATA_", report_options='custom=true')`  

- This works and is useful for us in the 0.8.x master branch and we are able to get the data required. It's not a great way to do this right now as we are modifying the package itself, and is difficult to redo each time we build our docker containers.

- Could you help us with getting this on the master branch containing the 0.8.x version? We are happy to raise a PR as well.

**Comment by GriceTurrble** [comment]
Correcting issue for 1.0dev in PR #247.

0.8 version has no `report_options` available, and adding them would technically be a bump to a 0.9. Are you prevented from upgrading into the 1.0dev branch currently?

**Comment by Mitalee** [comment]
Yeah we were hoping to jump straight to SP-API, moving to 1.0 from 0.8.x would mean refactoring in quite a few places..
