### ISSUE TITLE
Runtime Error 

### ISSUE THREAD

**Issue by xlcheese** [python-amazon-mws/python-amazon-mws#249]
I've been running this fine for a while.  I'm now getting this error.  Any pointers on how to fix would be greatly appreciated!

`    from mws import mws
  File "/usr/local/lib/python2.7/dist-packages/mws/__init__.py", line 4, in <module>
    from .mws import *  # noqa: F401, F403
  File "/usr/local/lib/python2.7/dist-packages/mws/mws.py", line 369
    output.append(f"metadata:{key}={outval}")`

**Comment by GriceTurrble** [comment]
`/usr/local/lib/python2.7` indicates you are working in Python 2.7, which is no longer supported. Please update to Python 3.6+.

**Comment by xlcheese** [comment]
Thanks!
