### ISSUE TITLE
How to get "Sponsored Products Advertised product report"

### ISSUE THREAD

**Issue by fkhjoy** [python-amazon-mws/python-amazon-mws#250]
I checked all the report type but didn't find something which contains this advertising report.
Can you please tell me if I missed something?
I would be glad if someone gives feedback fast.

Advertising reports are [here](advertising.amazon.com)
Thanks.

**Comment by Bobspadger** [comment]
I believe this is all under the amazon advertising api, not the market place api.

https://advertising.amazon.com/API/docs/en-us/reference/2/profiles
