### ISSUE TITLE
InvalidParameterValue error under python 3.9.2 with mws 0.8.12

### ISSUE THREAD

**Issue by pjv** [python-amazon-mws/python-amazon-mws#257]
I am using version 0.8.12 of mws and I have a little code that does a feed submit.

In my development environment which I have running on venv with python 3.9.2, I am getting an error from amazon that looks like this:

````
mws.mws.MWSError: <?xml version="1.0"?>
<ErrorResponse xmlns="http://mws.amazonaws.com/doc/2009-01-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>Timestamp 2021-03-10T20%3A08%3A42 must be in ISO8601 format</Message>
  </Error>
  <RequestID>1d289d47-28e6-4352-a3e4-33657df32e96</RequestID>
</ErrorResponse>
````

Digging through the stack trace it looks like amazon seems to be choking on the timestamp that is generated by the relatively new function `mws_utc_now()` which lives in `/mws/future_utils/timezone.py`.

Does the error message look like it might be an encoding issue for the timestamp that is being sent to amazon? Or is amazon url-encoding what they are sending back in the error message?

FWIW, the same code that is causing the error above works fine on the production server under python 3.6.9 and mws version 0.8.6 (which is before `mws_utc_now` was released in version 0.8.11).

**Comment by Bobspadger** [comment]
If I decode the `2021-03-10T20%3A08%3A42` I get  `2021-03-10T20:08:42` which is a valid ISO8601 timestamp.

Just having a very quick peek at the code, and we use exactly the same utc time function in the dev branch, which I know is working with it happily.

Are you able to try again, and capture the request (you can get this as an attribute from the response), and you should be able to pluck out the original request url etc.

Rip out any api keys etc, and pop it here so we can see whats actually been sent regarding the timestamp if you can?

**Comment by GriceTurrble** [comment]
Possibly some parameter cleaning not acting properly. We've been bitten with that before, not sure if that made it to `master`.

A sample would be good to do some local testing.

**Comment by pjv** [comment]
I don’t seem to be able to get hold of the response object due to an HTTPError that the request is causing, but the error is puking back the following which might be what you are asking for (?):

````
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://mws.amazonservices.com/?AWSAccessKeyId=XXXXX&Action=SubmitFeed&FeedOptions=XXXXX&FeedType=_POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA_&MarketplaceIdList.Id.1=text%252Ftab-separated-values%253B%2520charset%253Dutf-8&Merchant=XXXXX&PurgeAndReplace=false&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2021-03-11T14%253A56%253A37&Version=2009-01-01&Signature=XXXXX
````

**Comment by Bobspadger** [comment]
Thats great thanks

`Timestamp=2021-03-11T14%253A56%253A37`

Is the important bit!

That decodes to `Timestamp=2021-03-11T14%3A56%3A37` which makes it look like we have double encoded the parameter.

**Comment by Bobspadger** [comment]
Just looking, and this made its way in on the `0.8.11` .

However, the code went from:

`'Timestamp': self.get_timestamp(),`

to

`"Timestamp": mws_utc_now(),`

For the actual calling of the timestamp , so I don't think the issue is with the timestamp itself, but on the parameter encoding.

I'm at work at present so don't have much more time to trace this through, I'll try to look later.

**Comment by pjv** [comment]
In case it matters, my feed.submit code looks like this:

`response = feed.submit_feed(txt.encode('utf-8'), feed_type, MWS_MARKETPLACE_ID, content_type)`

where: `content_type = 'text/tab-separated-values; charset=utf-8'`

(and `txt` is the actual feed data)

**Comment by pjv** [comment]
I dug into the backported future utils and found a solution. I don’t know if it’s a good solution.

In `future_utils/params.py` the method `clean_date` is doing this with timestamp parameters:

`return clean_string(val.isoformat())`

`clean_string` is doing a `urllib.parse.quote` to clean the string and it seemed to me that that is where the double-encoding might have happened.

So I replaced the line above in `clean_date` with this:

`return val.isoformat()`

...and I am no longer getting the timestamp error from Amazon.

**Comment by Bobspadger** [comment]
@pjv apologies for breaking stuff - but 0.8.13 is now on PYPI for you to upgrade to, this fixes this issue.
