### ISSUE TITLE
About Report API Issue

### ISSUE THREAD

**Issue by 854350999** [python-amazon-mws/python-amazon-mws#266]
It seems that when I requested a report in the EU, I specified the French marketplace_id, but it returned information from other EU countries to me. Is there any bug in this?

**Comment by GriceTurrble** [comment]
Unlikely on our side, to be honest. MWS uses the same endpoint, `https://mws-eu.amazonservices.com`, for the different EU marketplaces. Only requests that make use of a `marketplace_id` value (and specific to France, `A13V1IB3VIYZZH`, according to [docs](https://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html)) have a chance of being specific to that market. Even then, it's up to Amazon MWS how they respond to your request.
