### ISSUE TITLE
[Bug]: python 2.7 encoding error on pip install

### ISSUE THREAD

**Issue by thomas-upecom** [python-amazon-mws/python-amazon-mws#272]
### Python Version

3.6

### Python Amazon MWS (PAM) Version

0.8 (PyPI version / GitHub master branch / 'legacy')

### Has your copy of PAM been altered in any way?

No, I HAVE NOT made changes to the MWS code

### Describe the issue

Hi, 
On your readme you notify you still manage the repository for python 2.7. That s why i write you this issue :) 
When i try to install the master branch by pip . 
I have this issue :
```
      with open("README.md", encoding="utf-8") as readme:
 TypeError: 'encoding' is an invalid keyword argument for this function
```

Apparently , as i can see on other git repository , you need to change 
`with open("README.md", encoding="utf-8") as readme:`
by 
`open('README.md',"rb").read().decode('utf8')`

I don t know if it s working on python 3...

### MWS Credential check

- [X] I have removed my MWS credentials from any tracebacks and code samples

**Comment by GriceTurrble** [comment]
Sorry to say the readme is incorrect: the `master` branch is not tested against 2.7 any longer. The test suite runs in 3.6+. I'll update that note to clear up any confusion.

As to your issue, if you absolutely require running in 2.7, you are free to clone and change it to suit your needs. I cannot offer support for it, however.
