### ISSUE TITLE
MWS - subscriptions

### ISSUE THREAD

**Issue by Anthon02** [python-amazon-mws/python-amazon-mws#282]
Hi,

I am trying to access the subscriptions service using python. Is there a module that helps with that process?

Thanks

**Comment by Bobspadger** [comment]
You need to use Boto from amazon to communicate over the services - then you can use the subscriptions API in our module to subscribe how you would like.

**Comment by Anthon02** [comment]
Where in the mws.py is the subscription code? Are there any examples of how to use the code? I currently use mws.py to get product information and to access feeds. However the version I am using is about 2 years old.

**Comment by Bobspadger** [comment]
Code:
https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/apis/subscriptions.py

The original pull request where I have a few examples:
https://github.com/python-amazon-mws/python-amazon-mws/pull/67

And a very basic working example in this one here (I used it to quickly setup my subscriptions for testing)

https://github.com/python-amazon-mws/python-amazon-mws/issues/176

**Comment by Anthon02** [comment]
The version of mws I have on my machine is several years old. The directory files include 

__pycache__
mws                           53kb (some minor modifications)
offamazonpayments  6kb
utils                            8kb

`MARKETPLACES = {
    "CA": "https://mws.amazonservices.ca",  # A2EUQ1WTGCTBG2
    "US": "https://mws.amazonservices.com",  # ATVPDKIKX0DER",
    "DE": "https://mws-eu.amazonservices.com",  # A1PA6795UKMFR9
    "ES": "https://mws-eu.amazonservices.com",  # A1RKKUPIHCS9HS
    "FR": "https://mws-eu.amazonservices.com",  # A13V1IB3VIYZZH
    "IN": "https://mws.amazonservices.in",  # A21TJRUUN4KGV
    "IT": "https://mws-eu.amazonservices.com",  # APJ6JRA9NG5V4
    "UK": "https://mws-eu.amazonservices.com",  # A1F83G8C2ARO7P
    "JP": "https://mws.amazonservices.jp",  # A1VC38T7YXB528
    "CN": "https://mws.amazonservices.com.cn",  # AAHKV2X7AFYLW
    "MX": "https://mws.amazonservices.com.mx",  # A1AM78C64UM0Y8
    "AU": "https://mws.amazonservices.com.au",  # A39IBJ37TRP1C6
    "BR": "https://mws.amazonservices.com",  # A2Q3Y263D00KWC
}
`

Do I have to install the updated mws package as it appears to have changed substantially over the past few years or is there an earlier version of the subcriptions API? Does accessing MWS for products and feeds API the same as before?

**Comment by Bobspadger** [comment]
You will need to use a later version of the software from when I added that feature.

**Comment by Anthon02** [comment]
I was able to uninstall the old and install mws-0.8.15. Nothing broke. haha.

Where do I place the subscriptions.py API?

Also where are these scripts?
```
from credentials import creds
from helpers.mws_factory import MWSFactor
```

**Comment by GriceTurrble** [comment]
`credentials` and `helpers` don't look familiar. Must some third-party modules, or something from your previous fork?

`Subscriptions` is part of the develop branch, which is a long-running effort to refactor the package. The 0.8 version on PyPI does not contain it.

You're welcome to use our version from develop branch here on GitHub and make some minor adjustments to get that working in your application. That may be the easiest path forward.

Otherwise you would just need to copy some code from `mws/apis/subscriptions.py` into your own code base and hack things together that way.

Apologies for not having a cleaner path forward at the moment: have not had the time necessary to get this package up to where it should have been years ago. :)

**Comment by Bobspadger** [comment]
```
from credentials import creds
from helpers.mws_factory import MWSFactor
```

You are referring to some helper code from my example I'm afraid - they are not part of the mws library.

I have a credentials management system I wrote (but you may want to look at [dynaconf](https://www.dynaconf.com/)) and a little factory helper to give me the correct API I required with all the settings correct , both of these are safe to ignore :)

**Comment by Anthon02** [comment]
> Apologies for not having a cleaner path forward at the moment: have not had the time necessary to get this package up to where it should have been years ago. :)

No worries.

Is there a earlier version of aws that has subcriptions.py included? If so wouldn't that be easier?

Also when I try to run subscription.py using my current installation the first line of code 

`from mws import MWS`

 yields this error.

cannot import name 'MWS' from 'mws'

**Comment by Anthon02** [comment]
If possible, I would like some clear instructions on how to use the subscriptions API. I would be happy to pay for a consultation to help make this happen.

**Comment by Bobspadger** [comment]
Hi @Anthon02 

You will need to use the develop branch of the module to gain access to the subscriptions code, but don't worry, its fairly stable and is in reality pretty close to being the 1.0 release.

If you want help on the subscriptions part - join the slack channel, I'm away this weekend but around from Monday if you want some pointers.

Alex

**Comment by Bobspadger** [comment]
for other help - have a look at some examples I've been trying to work on:

https://github.com/python-amazon-mws/python-amazon-mws/pull/241

**Comment by Anthon02** [comment]
Is this the subscription code you are talking about?

https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/apis/subscriptions.py

**Comment by Bobspadger** [comment]
> Is this the subscription code you are talking about?
> 
> https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/apis/subscriptions.py

That is the interface for the MWS Subscriptions API yes.
