### ISSUE TITLE
Request for new maintainer

### ISSUE THREAD

**Issue by jameshiew** [python-amazon-mws/python-amazon-mws#34]
Unfortunately I cannot maintain this package any longer. There are some great PRs and I don't have the focus now to properly integrate them, but it would be a shame to let them sit still. If you think you'd be up for maintaining the package and have some experience with python-amazon-mws I can move this Github repo over to an organization and also transfer over the pip package.

**Comment by GriceTurrble** [comment]
If it's not being too forward, I'd be willing to take up maintenance for this package. I don't have an account to test with directly (at least not yet?), but I do have experience with the library and some thoughts on future improvements.

If you can, please set up an org to house the repo, and we'll go from there.

**Comment by Bobspadger** [comment]
I'm happy to help out, I'm using it in production so can test items.

**Comment by JasonCrowe** [comment]
@GriceTurrble Has my vote!

**Comment by jameshiew** [comment]
Thank you for the offers of help! @GriceTurrble I've added you as a contributor to the python-amazon-mws organization since you seem to know the most probably about the project - feel free to merge things into `develop` as you see fit. There isn't really a proper roadmap for the project so whichever features/PRs you think are best to release next can work there way into `master` (tag 0.7.5 or 0.8 for the next release) - I know there is a lot of Finances API stuff kicking around. Feel free to ping me if you need any assistance - I've turned off all auto-uploading to PyPI for the moment in `develop` branch.

**Comment by GriceTurrble** [comment]
Thank you kindly for adding me onto the project. I hope the changes I've put in thus far have been helpful.

Apologies to folks if you've gotten too many notifications on open issues or PRs lately, as I've been toying around with the available tools in the repo and the org. I think I'm about ready to calm it down. :)

In particular, I've added a roadmap project with a few ideas. I'm looking to get the remaining APIs squared away so that we can push the project to a 1.0.0 release in the near future. There is no timeline set, just the basic requirements outlined.

**Comment by jameshiew** [comment]
Thank you @GriceTurrble for the recent whirlwind of work on this project! It's really great you've stepped up - I'm sure a lot of people will appreciate your work and attention to the package so far, it has definitely been in need of attention for a little while!

Whenever you think is appropriate, you can make a PR to `master` for the next release - I'll have to look at how to transfer ownership of the pip package to a org account or to your PyPI account if you have one and an org account isn't possible.

I can help with uploading the next release if needed, and maybe a bit of testing, as I have access to a busy MWS account with FBA. I probably won't be able to be involved in the project much in the future though - let's close this issue once the PyPI package is transferred over.
