### ISSUE TITLE
Feature request: Always return list of items

### ISSUE THREAD

**Issue by Bobspadger** [python-amazon-mws/python-amazon-mws#36]
for example, when using the Orders.list_order_items method, it is always necessary to do

`isinstance(order_items.parsed.OrderItems.OrderItem, list)`

This is repetition on a grand scale, so could possibly do we fixing in the module.

It may not be sensible to make this happen for ALL parts of the module as it could cause problems. Possibly just in select 'pinch points'

**Comment by GriceTurrble** [comment]
If it is possible to make our ObjectDict iterable (as though it were a list with one element) by default, I would prefer that option. Selecting specific instances means inspecting output to make those changes, and the possibility of missing functionality if we don't include each and every point where it is needed.

That said, if the latter option seems more viable and someone can offer an example, I'm open to it, as well. The "need" for `isinstance(..., list)` is a definite pain point.

**Comment by Bobspadger** [comment]
I was looking at making the object_dict return a list for anything if it was not an itterable, but this would break so much stuff, that maybe 'picking and choosing' would be the better option.

maybe declare a class method/option that is a list of items that should be returned as a list, 
(not real options)

self.return_as_list = ['orderItems', 'product_options']

then in the object_dict a simple (pseudo example)

    if obj in self.return_as_list:
        if isinstance(obj, list)
           return obj
       else:
             return [obj]

and then a user can either overwrite / append to / remove the self.return_as_list when they create an instance of the object.

we won't break anything existing until someone decides to use the feature, at which point, its only their code that will be an issue, but as they have probably already done isinstance(thing, list) it should probably just carry on as normal ?

**Comment by GriceTurrble** [comment]
I have a fix incoming, which was actually created some time ago in the upstream (czpython) repo by another contributor. See here:

https://github.com/GriceTurrble/python-amazon-mws/blob/876494ee4551eb0dc8902c418961a81870a0bf8d/mws/utils.py#L48-L64

Personal testing (using example XML responses from MWS docs) shows this works as intended. An original list is returned as-is; a single element that is iterated is returned as an iterator with that one element; and this applies to `__iter__`, so it does not impact direct access.

**Comment by GriceTurrble** [comment]
This is now covered in `develop` branch, to be released on `master` in 1.0 release.
