### ISSUE TITLE
Deal with Amazon's throttling

### ISSUE THREAD

**Issue by Bobspadger** [python-amazon-mws/python-amazon-mws#37]
Currently its very easy to hit Amazon's api limits.

Is it worth:

a) Writing a helper system to deal with this in MWS
b) Using something existing outside of MWS (Like Tenacity)
c) Integrating Tenacity into the project as a dependancy

?

**Comment by JasonCrowe** [comment]
Bottlenose deals with this problem without any 3rd party dependencies. 

Check it out below:
https://github.com/lionheart/bottlenose/blob/master/bottlenose/api.py

**Comment by JasonCrowe** [comment]
Specifically the code starting at line 261.

        # throttle ourselves if need be
        if self.MaxQPS:
            last_query_time = self._last_query_time[0]
            if last_query_time:
                wait_time = 1 / self.MaxQPS - (time.time() - last_query_time)
                if wait_time > 0:
                    log.debug('Waiting %.3fs to call Amazon API' % wait_time)
                    time.sleep(wait_time)

            self._last_query_time[0] = time.time()

**Comment by Bobspadger** [comment]
Its kind of nice, but not sure it fits how Amazon do it on the MWS and their leaky bucket scenario

They don't appear to show us what the max qps is, and their docs that the API returns this in the headers is not showing to be true (for me at least) on the order_item_list call.

Tenacity for example, has an exponential retry, along with the ability to handle different errors with different retry styles

**Comment by GriceTurrble** [comment]
I would rather not add a dependency, if it can be avoided. I think we can roll our own solution very simply.

In previous work, I implemented a decorator similar to Tenacity's that would retry a request using exponential back-off. It was a fairly simple pattern to follow: we just need to check an error response for code `RequestThrottled` and redo our `make_request` call as needed.

**Comment by GriceTurrble** [comment]
Quick note from memory: throttling in that fashion is useful for a majority of the API, but Products works differently. Instead of a throttle request being retried momentarily, requests are throttled until the next specified reset time, within one hour. Best strategy there is probably to do nothing, allow the error to go back to the user, and let them handle it.

**Comment by agritheory** [comment]
I think it makes sense to approach the throttling problem with a decorate syntax, either with the library or imported for the developer's utility. The mws-based code I've inherited had a retry loop built in, but that's a solution makes the problem worse until you're sure it fails. Might be a good idea for the products API though, as you mention.

**Comment by Bobspadger** [comment]
I've had brilliant success with Tenacity so not looked much harder here, it was easy enough to deal with outside of this library so maybe there are other more important items to work on first?

**Comment by agritheory** [comment]
Has anyone done anything with consuming the headers? That seems like a logical place to start. 

```
Amazon MWS provides header values in each call response that show the hourly quota for the current operation; the number of calls remaining in tha quota; and the date and time when the quota will reset. For example:

x-mws-quota-max: 3600
x-mws-quota-remaining: 10
x-mws-quota-resetsOn: Wed, 06 Mar 2013 19:07:58 GMT
```

**Comment by samamorgan** [comment]
Just wanted to chime in on this in case it's helpful.

I've been handling request limits in my code like this:

`for i in self.timeout:
                try:
                    request = self.markets[region].get_report_request_list(
                        types=(report_type),
                        processingstatuses=('_DONE_'),
                        fromdate=from_date,
                        next_token=next_token,
                    )
                    break

                except mws.MWSError as e:
                    if e.response.status_code == 503:
                        logging.info(f'Limit hit, waiting for {i} seconds')
                        time.sleep(i)
                        continue
                    else:
                        raise e`

**Comment by Bobspadger** [comment]
I went with Tenacity on this for my production, it works fantastically well.

All you have to do is declare a custom exception class, and decorate your call, tenacity takes cares of the rest.

I can share some code examples if you want ?

**Comment by samamorgan** [comment]
@Bobspadger I'd be happy to see any code you use for this. I prefer not to use extra libs unless necessary, but I'm always interested in others approach.

**Comment by Bobspadger** [comment]
I have a ThrottleError:
```python

class ThrottleError(Exception):
    """
    We have been throttled by amazon, raise this to allow tenacity to kick in
    """
    pass


```


Then I have a function who's sole task is to call the API I needed and test the result, if we are throttled, it raises the `ThrottleError`

```python

@retry(retry=retry_if_exception_type(ThrottleError), wait=wait_exponential(multiplier=1, max=10))
def get_comp_price(products_api, asin_list):
    """
        Call the get_competitive_pricing_for_sku api, if we are throttled, raise ThrottleError and retry the call
        :param sku_list:
        :return:
    """
    try:
        competitive_prices = products_api.get_competitive_pricing_for_asin(
            asins=asin_list, marketplace_id=MARKETPLACE_ID)
        return competitive_prices
    except ChunkedEncodingError as e:
        log.error('Chunked encoding error {}'.format(e))
        return None
    except Exception as e:
        if e.response.status_code == 503:
            # log.debug('Throttled, exponential backoff')
            log.debug('THROTTLED')
            raise ThrottleError
        else:
            raise

```

This has my `retry` decorator on it (from Tenacity) and I have configured this to have an exponential wait retry so we slowly back off and get longer and longer between calls.



Then I have my main logic (pseudo code here)

``` python

def main():
    while True:
        get_comp_price(api, asin_list)

```

With tenacity you just need to make sure you pull out the function / api call you want retrying .

Normally having dependancies can be a pain, but this is one where re-inventing the wheel seemed pointless and this has worked brilliantly in production for a couple of years now.

Hope that helps

Alex

**Comment by threemonks** [comment]
Is this issue still be considered, or it is dropped? I have to add the exponential back-off myself as well, but then every time I want to update to latest code base, I have to copy the entire code base and add throttling handling myself. It seems to me it is very important to have throttling handled in the API method itself for the library, because application code that calls these API methods usually does more than just calling the API call, therefore would not be the best place to handle the throttling and retry logic.

**Comment by Bobspadger** [comment]
This doesn't sound right - you should not need to edit the code base as mws is an importable module.

Import mws, and create an API, then wrap this with tenacity.

If you go this route, any update to mws will be transparent when you do `pip install mws --upgrade` etc

Don't go editing the mws module  :)

Feel free to hit me up on our slack channel if you want some more help.

**Comment by GriceTurrble** [comment]
Partly to help your current issue and partly for my own notes, if we want to incorporate this in near future:

An old project of mine (itself running an old fork of PAM) handles throttling in a manner similar to the following:

```python
from functools import wraps
import time

from requests import ConnectionError
from requests.models import DEFAULT_REDIRECT_LIMIT

from mws.errors import MWSError

CONNECTION_RETRIES = 3
"""Number of retries to attempt if there are connection errors,
independent of throttling events.
"""

DEFAULT_TIMEOUTS = [0, 2, 4]
"""If no timeouts supplied to decorated method,
use these as defaults. Each is a number of seconds before
trying again.
"""

def response_has_error(resp) -> bool:
    return "Error" in resp._dotdict


def response_is_throttled(resp) -> bool:
    if not response_has_error(resp):
        return False
    return resp._dotdict.Error.get("Code", "") == "RequestThrottled"


def throttle_controlled(timeouts=None):
    """Wraps an MWS request function so that it will attempt to re-run itself
    in the event of a throttling or disconnection error.
    """
    timeouts = sorted(timeouts) if timeouts else DEFAULT_TIMEOUTS
    timeouts.insert(0, 0)
    # Add an initial 0-second "timeout" that simply allows the first
    # request to go through without a pause. This is so we can run timeouts
    # at the start of a loop before running a request, rather than at the end
    # where the final timeout might just pause for X seconds before doing nothing.

    def control_decorator(request_func): # pylint: disable=C0111
        @wraps(request_func)
        def control_wrapper(*args, **kwargs): # pylint: disable=C0111
            retry_for_connection_error = True
            for _ in range(CONNECTION_RETRIES):
                retry_for_connection_error = False
                for timeout in timeouts:
                    time.sleep(timeout)

                    try:
                        # Request function runs here
                        resp = request_func(*args, **kwargs)
                    except ConnectionError:
                        # requests connection problem, did not reach Amazon.
                        retry_for_connection_error = True
                        # break the timeouts loop, continue on outer loop
                        break
                    if response_is_throttled(resp):
                        # retry for throttling
                        continue
                    break
                else:
                    # Throttle limits reached (no breaks hit on inner loop).
                    raise MWSError((
                        "Operation stopped by Amazon throttling. "
                        "Please try again later."
                    ))
                if retry_for_connection_error:
                    # Wait 1 second, then re-run CONNECTION_RETRIES loop
                    # Starts a new set of timeouts on a new connection attempt.
                    time.sleep(1)
                    continue
                break
            else:
                # Connection retries limit reached (no breaks on connection retries loop)
                raise MWSError((
                    f"Maximum connection attempts reached ({CONNECTION_RETRIES}). "
                    "Please try again later."
                ))
            return result
        return control_wrapper
    return control_decorator
```

I then subclass the APIs and include this decorator on specific requests:

```python
from .decorator import throttle_controlled
# the above decorator function

from mws import InboundShipments

class MyInboundShipments(InboundShipments):
    ...
    # using the default timeouts:
    @throttle_controlled
    def create_inbound_shipment(self, *args, **kwargs):
        return super().create_inbound_shipment(*args, **kwargs)
        
    # using custom timeouts:
    @throttle_controlled(timeouts=[1, 8, 13])
    def list_inbound_shipments(self, *args, **kwargs):
        return super().list_inbound_shipments(*args, **kwargs)
```

You might also wrap the base `make_request` method, but taking control of specific requests is more useful, as each can have different timeout requirements.

Using something like [Tenacity](https://github.com/jd/tenacity) as @Bobspadger mentions, you can do something very similar, just using a `retry` decorator in place of my `throttle_controlled` version.

My goal above was to explicitly check for the `RequestThrottled` code that indicates throttling, so that it would not retry legitimate errors needlessly and so that `requests.ConnectionError` problems could be handled on their own, without triggering timeouts.

Note that the different MWS API sections act differently. I found that `Products`, for example, would respond with a very particular message containing `reset on` followed by a timestamp. No request will pass through until that time passes, so I would simply get the diff from that timestamp and current time and `time.sleep` for that long.

Finally, the same kind of subclassing pattern can help you extend PAM for your own needs. For example, I added hooks in `make_request` that would log Request IDs to the database; and overloaded `InboundShipments.__init__` to inject the `from_address` from the application's configuration.

**Comment by threemonks** [comment]
This is similar to what I did, except that I saved a copy of the module locally, modified and wrapped the API calls with retry with exponential backoff. I will try your suggestion in my next update, import mws module, subclass it and then wrap the API calls within the subclass  with throttle retry logic. It is still lots of methods that I need to wrap in the subclass. So it would be best if this logic is implemented in the library directly.

**Comment by GriceTurrble** [comment]
Agreed, and I'll consider that in the future when I get a little more time.

Contributions welcome, of course. :)

**Comment by shtlrs** [comment]
@Bobspadger  Hi, 
How can one join the slack channel for these kinds of discussions ?

**Comment by Bobspadger** [comment]
@shtlrs https://pythonamazonmws.slack.com/join/shared_invite/enQtOTcwNTAzNjI4OTc2LTQyMzk1YzIxNTU0MmE1MWE0ZDUzZjBhMjI2ODZhNTQ5Mjk3ZTUyOGFkODk1N2Q2NjczZjY2M2U3NzAzNDU4ZTc#/shared-invite/email
