### ISSUE TITLE
Increase test coverage for requests by checking input params

### ISSUE THREAD

**Issue by GriceTurrble** [python-amazon-mws/python-amazon-mws#38]
Given the nature of the package, it is not currently possible to test all the different request methods through automation, since testing responses requires valid Amazon Seller credentials to make a connection. Even if we were able to use Seller credentials to perform an automated test, there is no (last I heard) testing environment on the MWS side, so any request made has potential to wreak havoc in that Seller's production environment.

Rather than try to check MWS's response, we can make testing simpler by stopping short of actually sending a request. All that is really needed is to get either the parameter dict or the request string that a given request method constructs, testing that against pre-set data.

---

I am thinking the best option is to have an attribute on the base `MWS` class, something like `debug_params`, as a boolean. When testing, we just switch it to True, then `make_request` would be set to return the full param set instead of sending a request. Our test cases for these requests then need to initialize the APIs and switch on this "debug mode" in order to proceed.

This does mean that *some* code would not be covered, specifically the latter half of `make_request` that builds a DictWrapper or DataWrapper from the response. We can find some ways to cover that separately later, though, since right now I think covering the request methods is more important.

**Comment by GriceTurrble** [comment]
*Applied discussion label, as I'd like input from others before moving forward.*

**Comment by Bobspadger** [comment]
You are correct, there is no test / sandbox environment for MWS at amazon, so sending automated test calls would have the possibility of ruining someones account.

some pre-set test data is probably the way to go

**Comment by GriceTurrble** [comment]
Framework for this test coverage added by updates ala #54.
