### ISSUE TITLE
Should `'User-Agent'` header have version pushed?

### ISSUE THREAD

**Issue by GriceTurrble** [python-amazon-mws/python-amazon-mws#39]
See: https://github.com/python-amazon-mws/python-amazon-mws/blob/6fc53edb4fe1b529bb94835744d1aa86171d0e03/mws/mws.py#L223

This looks like a version string added to the `User-Agent` header. I don't know best practices in this case, so the question: should we pull the project version in here to use an up-to-date version string when making new requests?

**Comment by jameshiew** [comment]
Yes this is the user-agent string from upstream, it doesn't seem like they updated it either

Maybe put a `__version__ = '0.8.0'` in `mws/__init__.py` and then interpolate it into this string? I have seen that pattern used elsewhere I think

**Comment by GriceTurrble** [comment]
Temporary fix, I pushed the version manually here:

https://github.com/python-amazon-mws/python-amazon-mws/blob/91d77f9df3d8f36a08b415b674b83f77e311db3d/mws/mws.py#L228

Will leave open and take the direction, single-sourcing the version in a future release.

**Comment by GriceTurrble** [comment]
Covered by refactor pushed ala issue #54.
