### ISSUE TITLE
Sending inventory updates or creating new products

### ISSUE THREAD

**Issue by JasonCrowe** [python-amazon-mws/python-amazon-mws#40]
Is there a class for making inventory updates or creating new products?

**Comment by GriceTurrble** [comment]
These types of actions require use of the MWS **Feeds** API. See Amazon documentation [here](http://docs.developer.amazonservices.com/en_US/feeds/Feeds_Overview.html).

`python-amazon-mws` has a `Feeds` class for basic coverage of this API, but you will need to follow Amazon's documented procedures to make the best use of it.

**Comment by JasonCrowe** [comment]
Thanks! I appreciate all the work you're doing here! I am just getting started with this code, so please accept my apologies for all the questions.

**Comment by Bobspadger** [comment]
here's an example for you that I have working


```
feed_header = 'sku\tproduct-id\tproduct-id-type\tprice\titem-condition\tquantity\tadd-delete\n'
feed_row_template = '{}\t{}\t{}\t{}\t{}\t{}\t{}'

products_to_update = DO_DB_CALL_HERE

for product in products_to_update:
        feed_row = make_feed_row(update_type, feed_row_template, product)
        feed_row_list.append(feed_row)

feed_data = feed_header + '\n'.join(feed_row_list)
feed_data = feed_data.encode('utf8')
result = feeds_api.submit_feed(feed_data, '_POST_FLAT_FILE_INVLOADER_DATA_')
```
the make_feed_row() function is a simple .format function that just adjusts the output based on some logic here

example:
feed_row = feed_row_template.formate(sku, order_id, price) etc etc

**Comment by JasonCrowe** [comment]
That's nice! As soon as I get my next order I am going to give it a "go".

Thanks!

**Comment by Bobspadger** [comment]
I have it working in production.

I have several different call types, which all use the same module.

I use argparse to choose the type of call, and adjust the `feed_header` and `feed_template` as required.

All I do is pull the relevant info out the db, and bosh, off it goes.

**Comment by xTwindad** [comment]
Hi, I have this error when I try to upload my file;
(naturally I've double checked the keys)
-['exception']	MWSError('<?xml version="1.0"?>\n<ErrorResponse xmlns="http://mws.amazonaws.com/doc/2009-01-01/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>InvalidAccessKeyId</Code>\n    <Message>The AWS Access Key Id you provided does not exist in our records.</Message>\n  </Error>\n  <RequestID>...</RequestID>\n</ErrorResponse>\n',)	MWSError

**Comment by GriceTurrble** [comment]
Do you get that response for a particular request method or for all of them?

And can you provide a sample of the code that is failing?

**Comment by xTwindad** [comment]
Hi @GriceTurrble thank you for reply,
I solved..it was my error in passing parameters
Seems to work now
If anyone interested maybe I can share my code later

**Comment by xTwindad** [comment]
Sorry,maybe is a dumb question:

for example, I had to send one feed to italian marketplace and a different one to Spain marketplace;
we have declared 
```
MARKETPLACES = {
    "CA": "https://mws.amazonservices.ca",  # A2EUQ1WTGCTBG2
    "US": "https://mws.amazonservices.com",  # ATVPDKIKX0DER",
    "DE": "https://mws-eu.amazonservices.com",  # A1PA6795UKMFR9
    "ES": "https://mws-eu.amazonservices.com",  # A1RKKUPIHCS9HS
    "FR": "https://mws-eu.amazonservices.com",  # A13V1IB3VIYZZH
    "IN": "https://mws.amazonservices.in",  # A21TJRUUN4KGV
    "IT": "https://mws-eu.amazonservices.com",  # APJ6JRA9NG5V4
    "UK": "https://mws-eu.amazonservices.com",  # A1F83G8C2ARO7P
    "JP": "https://mws.amazonservices.jp",  # A1VC38T7YXB528
    "CN": "https://mws.amazonservices.com.cn",  # AAHKV2X7AFYLW
    "MX": "https://mws.amazonservices.com.mx",  # A1AM78C64UM0Y8
}
```
 so the endpoints for all european market are the same (https://mws-eu.amazonservices.com);
how to point to specified marketplace id like APJ6JRA9NG5V4 or A1RKKUPIHCS9HS?

**Comment by GriceTurrble** [comment]
The endpoints for MWS are a bit different from the marketplace ID (the naming of the above constant is a bit confusing here, so we may adjust that a little in the future).

Amazon documentation has details here: http://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html

*(side note: our code are missing the marketplace IDs for Australia and Brazil)*

**Endpoints** are used to send data to an MWS server somewhere in the world by the URL of that endpoint. According to their docs, "Calls to Amazon MWS must go through an endpoint for a region or marketplace where the seller is registered to sell": that is, your SellerId must be registered in the region for that endpoint in order to access it.

**Marketplaces** are used as arguments to MWS APIs to specify which Amazon market the request pertains to. In calls like `submit_feed` for instance:

https://github.com/python-amazon-mws/python-amazon-mws/blob/6c67339c5a1f99937c60f809526ce06a4ada460e/mws/mws.py#L339-L351

...you would provide a list of `marketplaceids`* for the feed. For the Italy market, this would be `"APJ6JRA9NG5V4"`. You should be able to use this MarketplaceId to submit a feed for the Italy market, regardless of *your* MWS endpoint (above).

**in current `develop` branch and later 1.0 release, this argument is named `marketplace_ids` instead.*

**Comment by xTwindad** [comment]
Thank you, I didn't realize that I had to pass marketplaceids to submit_feed

**Comment by ssheduardo** [comment]
Some example to read a file txt for send throught submitFeed?

**Comment by Bobspadger** [comment]
reading files in python is probably out of the scope of this project but an example would be something like this:  (omitting setting up the api etc in the first place)

```py
with open('myfile.txt' , 'r') as f:
    result = feeds_api.submit_feed(f, '_POST_FLAT_FILE_INVLOADER_DATA_')
```

**Comment by ssheduardo** [comment]
The problem the loop file is:
- The first line is the column information (sku, description, type, quantity, etc)

The ideal is load the file and send the content file into submit_feed, anyone help me?

**Comment by Bobspadger** [comment]
@ssheduardo I'll make some assumptions here that you are reading from a csv file or a tsv file?

Amazon require you send the headers in the file, so as long as you have the correct headers in there, and the file is the correct format (tab seperated) then you should just be able to upload it.

for us here, we create the file on the fly from database information, and send the headers as such:

```py
feed_header = 'sku\tproduct-id\tproduct-id-type\tprice\titem-condition\tquantity\tadd-delete\tmerchant-shipping-group-name\n'
 ```


We could send the file columns in any order , as long as they are correctly labeled.

**Comment by ssheduardo** [comment]
Ok, I understand that first build the header and body (strings).
I try create manually the data example.

I have a demo in Java (I only working with php / python), this example send a file with this flat: _POST_FLAT_FILE_LISTINGS_DATA_, previously the file is did read as Stream.

I can load file as stream and send to submit_feed?

Thanks @Bobspadger

**Comment by ssheduardo** [comment]
When send the string, the script return this error

```
Traceback (most recent call last):
  File "test-amazon.py", line 32, in <module>
    result = feeds_api.submit_feed(feed, '_POST_FLAT_FILE_INVLOADER_DATA_')
  File "/home/demo/anaconda3/lib/python3.7/site-packages/mws/mws.py", line 351, in submit_feed
    md = calc_md5(feed)
  File "/home/demo/anaconda3/lib/python3.7/site-packages/mws/mws.py", line 75, in calc_md5
    md5_hash.update(string)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by Bobspadger** [comment]
```py
TypeError: Unicode-objects must be encoded before hashing
```

You will have some unicode characters in your string by the sounds of thigs

**Comment by ssheduardo** [comment]
I not understand same error, see the example:

```
feed = 'TemplateType=sports\tVersion=2016.0601\t\tOferta-Información de ofertas - Estos atributos se utilizan para que los clientes puedan comprar su artículo en la página web.\n' \
    + 'SKU\tNombre del artículo\tActualizar o borrar\tPrecio de publicación\tCantidad\tPrecio\tPrecio en oferta\tFecha de comienzo de la oferta\tFecha de finalización de la venta\tUnidad de medida peso del artículo en display	Peso del artículo en display\n' \
    + 'item_sku\titem_name\tupdate_delete\tlist_price\tquantity\tstandard_price\tsale_price\tsale_from_date\tsale_end_date\titem_display_weight_unit_of_measure\titem_display_weight\n' \
    + '84\tActualizar parcialmente\t409\t\t\t\t\t\t'

result = feeds_api.submit_feed(feed, '_POST_FLAT_FILE_INVLOADER_DATA_')
```

```
Traceback (most recent call last):
  File "test-amazon.py", line 32, in <module>
    result = feeds_api.submit_feed(feed, '_POST_FLAT_FILE_INVLOADER_DATA_')
  File "/home/demo/anaconda3/lib/python3.7/site-packages/mws/mws.py", line 351, in submit_feed
    md = calc_md5(feed)
  File "/home/demo/anaconda3/lib/python3.7/site-packages/mws/mws.py", line 75, in calc_md5
    md5_hash.update(string)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by NicolaErario** [comment]
`feed = feed.encode('utf-8')`

**Comment by ssheduardo** [comment]
@NicolaErario work for me.

Thanks you.

**Comment by ssheduardo** [comment]
This is correct when add my MarketPlaceId

`result = feeds_api.submit_feed(feed, '_POST_FLAT_FILE_LISTINGS_DATA_','','XXXXXXXXX')`

**Comment by ssheduardo** [comment]
The problem is, when not send a marketplaceid, the amazon try send the information to many marketplace :( 
Is correct as add the markeplaceid in the method submit_feed?
@NicolaErario  anyone solutions?

**Comment by NicolaErario** [comment]
@ssheduardo 

`result = feeds_api.submit_feed(feed, '_POST_FLAT_FILE_LISTINGS_DATA_', marketplaceids='XXXXXXXXX')`

in your code there are quotes and commas not needed;
I don't push my feeds to all the marketplaces, so I use the "submit_feed" with marketplaceids that I need

**Comment by ssheduardo** [comment]
@NicolaErario 
Adding the marketplaceids='XXXXXXXXX',  amazon set correctly the marketPlaceId
Thanks you.

**Comment by ssheduardo** [comment]
This example has worked for me.
```

# coding=utf-8
import mws
import os

#################################

MWS_ACCOUNT_ID = 'YOUR-ACCOUNT-ID'
MWS_ACCESS_KEY = 'ACCESS-KEY'
MWS_SECRET_KEY = 'SECRET-KEY'
MARKETPLACEID = 'YOUR-MARKET-PLACE-ID'
#################################

file_amazon = 'your-file.txt'
feeds_api = mws.Feeds(
    access_key=MWS_ACCESS_KEY,
    secret_key=MWS_SECRET_KEY,
    account_id=MWS_ACCOUNT_ID,
    region='ES',  # if necessary
)

service_status = feeds_api.get_service_status()
print(service_status.parsed)

#send file
feed = open(file_amazon, "r").read()

feed = feed.encode('utf-8')

result = feeds_api.submit_feed(feed, '_POST_FLAT_FILE_LISTINGS_DATA_',marketplaceids=MARKETPLACEID)

print(result.parsed)
```

**Comment by NicolaErario** [comment]
As good practice I suggest you to use:
```
with open ('file_amazon') as f:
    feed = f.read()
```
as suggested by python doc (7.2);
@ssheduardo

**Comment by Bobspadger** [comment]
as @NicolaErario has suggested @ssheduardo try to use the `with` context helper as this will close the file handle after use.

Your code currently leaves the `feed` file open

**Comment by ssheduardo** [comment]
Thanks @NicolaErario  and @Bobspadger
