### ISSUE TITLE
Incorporate methods from `python-amazon-mws-tools`?

### ISSUE THREAD

**Issue by GriceTurrble** [python-amazon-mws/python-amazon-mws#41]
Came across this recently: [`python-amazon-mws-tools`](https://github.com/ziplokk1/python-amazon-mws-tools).

The tools are meant as a companion for `python-amazon-mws` (as forked from the upstream by czpython), adding wrappers to process incoming data into more meaningful Python objects.

I haven't dug into it much, but it might be a good jumping-off point to adding some more intelligent behavior into the base project.

**Comment by agritheory** [comment]
So I'm just getting into this project but it seems that these wrappers are pretty nice. I picked up the project from another team where they had written their own wrappers to integrate with a framework, which I understand better. If I were to guess, it seems like most people would be writing their own wrappers, when it may be good to provide an API layer above the current one. In favor.
