### ISSUE TITLE
Feature Request: Merchant Fulfillment

### ISSUE THREAD

**Issue by Bobspadger** [python-amazon-mws/python-amazon-mws#48]
http://docs.developer.amazonservices.com/en_UK/merch_fulfill/MerchFulfill_Overview.html

Amazon are really pushing their seller fulfilled prime service, which requires labels to be produced via their system. Link above.

**Comment by cmchecha** [comment]
Check this fork https://github.com/cmchecha/python-amazon-mws

**Comment by Bobspadger** [comment]
@cmchecha you legend! Are you using this in production yet? If so, is it worth putting a pull request into this repo to get it merged in?

I was about to start working on my version but you look like you have won the day :)

**Comment by cmchecha** [comment]
@Bobspadger I just finished yet haha, I'll be testing it in the coming days.

**Comment by Bobspadger** [comment]
@cmchecha  ah ok - for some reason I didn't clock the date on the commits!, 

I'm trying to work out if I can test it as well. Sadly Amazon don't have a test system so I need to work out a way of testing this without causing an order issues

**Comment by GriceTurrble** [comment]
Looks good at first glance. Feel free to issue a PR and we can review from there. :)

**Comment by GriceTurrble** [comment]
[Note, PR #50 covers]

**Comment by GriceTurrble** [comment]
#50 and #53 cover this request. Issue appears resolved.
