### ISSUE TITLE
parse finance api response

### ISSUE THREAD

**Issue by elcolumbio** [python-amazon-mws/python-amazon-mws#49]
I am struggling with the finance api response.
I want:
- select features
- robust and complete data

what i tried so far:
for me it seems not so straight forward.
https://gist.github.com/elcolumbio/dfbbc26e2585425e2f4d47879bc9c584

I would like to help building a wrapper to make it easier.

**Comment by GriceTurrble** [comment]
Sorry for the delayed response.

I'm struggling to understand exactly what your code is trying to do with the response data. What type of wrapper are you looking to build, what is your desired output, etc.?

**Comment by elcolumbio** [comment]
thanks for your response. Basically i want to rebuild something close to the settlement report.
For each eventtype (like shipment event) i create a table, thats why i flatten the api response.
I wrote rules to extract predefined features from the apiresponse and mapped them to column names.

I explicit name each part i extract of the tree in the apiresponse. The nested data parts of the tree, i can calculate with string formatting (like .replace('list', '').

Those common rules i found:
- simple key, value pairs -> easy take key value
- easy lists of dictionnaries -> easy each element is a simple key, value pair (like currencyamount and currencycode)
- difficult lists -> each item of the list has to be flattened into a row into the table (like its done in the settlement report).

**Comment by GriceTurrble** [comment]
> Basically i want to rebuild something close to the settlement report.

If that's the case, I would suggest not trying to reinvent the wheel, and instead use the `Reports` API to get a settlement report.

* [Documentation for Report API by Amazon](http://docs.developer.amazonservices.com/en_US/reports/Reports_Overview.html)
* [ReportType enumerations for Settlement Reports](http://docs.developer.amazonservices.com/en_US/reports/Reports_ReportType.html#ReportTypeCategories__SettlementReports)

If that doesn't cover your use case, and indeed you must use the `Finances` API, I can look into this in more detail soon.

**Comment by GriceTurrble** [comment]
Closing this as there does not appear to be an issue at this time. If there is, please feel free to come back and re-open.
