### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by lolcats4u** [python-amazon-mws/python-amazon-mws#51]
How would one request a full inventory report or list? There's support to use for specific skus but suppose I wanted to just know the entire inventory and dump it in a text file.

**Comment by GriceTurrble** [comment]
This is more of an MWS question than something specific to `python-amazon-mws`, but: what you're looking for is likely part of the `Reports` API. See [here](http://docs.developer.amazonservices.com/en_US/reports/Reports_Overview.html) for Amazon documentation.

In your case, you may want to create a `_GET_MERCHANT_LISTINGS_ALL_DATA_` report. Other report types are detailed in the [ReportType enumeration](http://docs.developer.amazonservices.com/en_US/reports/Reports_ReportType.html).

On our side of things, you can schedule reports, get their status, and request to download them through our `Reports` API class; but you will need to follow Amazon's guidelines (documentation above) on which requests to send at what times.

**Comment by lolcats4u** [comment]
Thanks, I appreciate the help. I'm new to the amazon API, so I sometimes find their documentation hard to read. >.<
