### ISSUE TITLE
General Announcements [2019-03-26: getting back in the swing of things]

### ISSUE THREAD

**Issue by GriceTurrble** [python-amazon-mws/python-amazon-mws#54]
For lack of a solid option at the moment and a lack of desire to set up a proper blog right now, I am using this issue as an announcement. So: hi, folks. 😃 

### 2018-06-01
We've had some progress lately, mainly thanks to contributors donating their time. Thank you to those who have added content recently to improve the project. :) [*(full comment)*](https://github.com/python-amazon-mws/python-amazon-mws/issues/54#issuecomment-393930822)

### 2018-05-08
**Quick update**: we have detached python-amazon-mws from the original upstream repo, so this is now a "normal" repository. [*(full comment)*](https://github.com/python-amazon-mws/python-amazon-mws/issues/54#issuecomment-387454140)

### 2018-03-10
**Update to an update**: I've merged `feature-request-testing` branch to `develop`. This provides a framework for request method automated testing throughout the project, with some example tests provided for the Inventory API. [*(full comment)*](https://github.com/python-amazon-mws/python-amazon-mws/issues/54#issuecomment-372063251)

---

*Original post from 2018-03-10 follows*

All current PRs have been merged and accepted into the `develop` branch, bringing that branch up-to-date with the current set of changes. Now's a good time for a change I've been working on, **separating the `mws` module into component modules**.

## API modules
Each MWS API will be covered by the same class of the same name as before. Now, however, code will be moved into the `apis` sub-directory. Each API lives within its own module, which allows for easier editing in future as we don't need to sift through the monolithic `mws` module to make those changes.

As much as possible, I've tried to ensure that the changes remain backwards-compatible:

* You should still be able to access API classes using the style `from mws import ApiClass`.
* **breaking change**: if your code relied on an import such as `from mws.mws import ApiClass`, this will no longer work. You must edit downstream code to match `from mws import ApiClass`
* Alternatively, `from mws.apis import ApiClass` will work just the same, though this not necessary.
  * You could get *even more* specific, if you like: `from mws.apis.inventory import Inventory`. This is almost positively *not* necessary for accessing the API class.

## New space for API-specific code
Because APIs are now separated into component modules, there is now ample space for additional data, constants, and functions specific to that API. For example, we may expand on sections such as the `Reports` API to include constants for each [ReportType enumeration](http://docs.developer.amazonservices.com/en_US/reports/Reports_ReportType.html), which can aid both internal code (adding checks for the enumeration used) and downstream development (providing easy access to the enumeration types, relieving some of the pressure on end users to dive into Amazon MWS documentation every time they want to make a change).

An example of this will be present in the InboundShipments API, with the use of the separate `parse_item_args` method (previously a method of the InboundShipments class).

## Decorators
With the introduction of the InboundShipments API, we provided a decorator for `next_token_action`, allowing users to call the same request method with a `next_token` kwarg to automatically call that method's `ByNextToken` action. This decorator was previously housed in the `utils` module.

With this update, I've moved it into its own `decorators` module, which can be home to other useful decorators in future, if necessary.

## Roadmap
As mentioned, this change is being merged into the `develop` branch today. I would have waited until after a 0.9 release first, but I felt it best to push it earlier so that others can play around with it as we continue to move forward in fixing up the project. Further, since there are some (albeit minor) breaking changes with this merge, a new minor release just won't cut it.

Therefore, the next release will be **1.0**. I'm looking to bolster the functionality of the project so that it can cover a majority of use-cases and function as the de facto version of `python-amazon-mws` in the wild. The "roadmap" project will be updated later today to reflect this.

On that last note ("being the de facto version of `python-amazon-mws`"): once we move to a 1.0 release, I will be requesting that this project be separated from its upstream (by czpython). That will provide us with a bit more control over the project and some additional tools (searching this repo is not currently possible, because it is still technically a fork).

## Q&A
Feel free to post questions here regarding these changes, future plans, and so on. Thank you.

**Comment by GriceTurrble** [comment]
## Update to an update
I've merged `feature-request-testing` branch to `develop`, as well. This provides a framework for request method automated testing throughout the project, with some example tests provided for the Inventory API.

We would prefer that PRs from this point forward also include some test coverage for any methods being added, but this is not a strict requirement.

Thank you. :)

**Comment by Bobspadger** [comment]
Its worth noting that quite a few of the arguments for the api's have changed, which will break code.

I understand why this has been done (mirroring Amazon's naming) but its worth highlighting this as I had to go refactor a whole bunch of calls.

**Comment by GriceTurrble** [comment]
Yes, apologies for the trouble on that one, if you're using the develop branch in production. Please be aware that branch is likely to change frequently in the future, though from now on I will focus on separate branches and merges to compartmentalize those changes.

As for the argument name changing, as I built tests for the APIs, I kept noticing different APIs and even different methods within the same API classes of `python-amazon-mws` were using different argument names for essentially the same information. The inconsistency is a pain that will only serve to bite new users as they try to use this tool later on.

I intend to have documentation for all API classes and their methods ready for a 1.0 release (timeline not yet determined). Until then, the current state of `develop` branch (as of time of writing this) *should** remain the standard, unless some glaring inconsistency pops up.

**Comment by Bobspadger** [comment]
I fully understand the reasons :)

just thought it best to point out incase anyone else was messing with it.

I'm using the develop branch in production, but as a fork from my own repo, so changes won't just creep in :)

I'll try to write some tests when I get a chance for some of it, but paying jobs come first at the moment :/

**Comment by GriceTurrble** [comment]
## Update
For those watching progress on this project, no, I've not forgotten. :)

Past weeks have been busy with personal life stuff, though nothing really serious. This coming weekend would be my free time to get some work completed on items here, but it, too, is booked up with personal stuff and the Easter weekend.

Likely to have some work flowing in a week or so, to help push us towards a 1.0 release within the next month or two (at the most). Until then, I welcome any and all contributions to add more test coverage, missing request methods and APIs, helper methods, and so on.

Happy Friday, folks.

**Comment by GriceTurrble** [comment]
**Quick update**: we have detached `python-amazon-mws` from the original upstream repo, so this is now a "normal" repository. This enables code searching and cleans up some workflows (we will no longer be asked to open PRs to the upstream, for instance).

The upstream's maintainer has archived (made that repo read-only) and added links pointing here. I imagine folks watching there may move over to our repo in due time.

Thanks to @czpython for their work maintaining the API for as long as they did and giving us a good starting point. We'll take it from here. Feel free to stop by and contribute if you see fit. :)

**Comment by GriceTurrble** [comment]
We've had some progress lately, mainly thanks to contributors donating their time. Thank you to those who have added content recently to improve the project. :)

We also have some movement on a PR #75 to convert from the internal "XML2Dict" object to the external `xmltodict` as a new dependency. This offloads the work of converting XML responses to dict-like objects into a more specialized package, so hopefully we can focus on the details of MWS itself moving forward.

There's still work to be done on that overhaul to ensure good output across a variety of request types and response structures, including file-like responses from the Reports API. I am setting some time aside this weekend to run tests on the code provided by @elcolumbio against MWS example responses. Any assistance from contributors with working production environments is much appreciated.

---

Things are moving slowly but surely towards a 1.0 release with full coverage of MWS. Once we have that release, we should be in a good spot to add features to help with response data parsing and manipulation.
