### ISSUE TITLE
Need a "clean" method for parameter validation

### ISSUE THREAD

**Issue by GriceTurrble** [python-amazon-mws/python-amazon-mws#56]
While writing some request method tests recently, I came across some mild confusion, conceptually speaking.

We perform a parameter validation for `datetime`s within the `make_request` method, here:

https://github.com/python-amazon-mws/python-amazon-mws/blob/7dd4a509e0f699885383d9b638e8d9b24bb57875/mws/mws.py#L249-L251

Aside from this, params are not validated much further. The next time they are touched in a similar fashion is inside `calc_request_description`:

https://github.com/python-amazon-mws/python-amazon-mws/blob/7dd4a509e0f699885383d9b638e8d9b24bb57875/mws/mws.py#L81-L84

Here, the parameter value passes through `str` and `urllib.parse.quote` (on Python 2, `urllib.quote`). That `str` conversion is necessary to prevent errors when passing the value through `quote`, which is fine.

---

**Problem**: These two spots represent two different points of input validation that only A) convert `datetime` objects to strings in ISO-8601 format, and B) convert any other value to `str` (while not catching any exceptions that could be raised by `str`). While it isn't breaking much, it limits options for further validation, as well as adding some confusion as to whether and/or when any validation is being performed.

---

**Solution**: Would like to write a "clean" method that all parameters pass through, taking the "raw" parameters as input and returning a "cleaned" version of the params dict. Downstream code should be able to rely on every value of the parameter dict being a string **or** a useful exception being raised if a parameter value cannot be converted.

The "clean" method should be called inside the `make_request` method, in about the same spot as the current `datetime` validation code (the call to the "clean" method should replace that validation, in fact).

---

At time of writing, I'm busy with test methods, day job, and home stuff. If anyone else wants to pick this off, feel free to do so.

**Comment by elcolumbio** [comment]
thank you @GriceTurrble for the great post.
My solution is simple:
```python
def clean_extra_data(extra_data):
    for key, value in extra_data.items():
        if 'date' in key.lower():
            assert isinstance(value, (datetime.datetime, datetime.date))
            extra_data[key] = value.isoformat()
        else:
            assert isinstance(value, str)
    return extra_data
```

**Comment by elcolumbio** [comment]
thanks, i will fix it.

**Comment by elcolumbio** [comment]
I tried to use duck typing. So it allows more inputs.

The date validation now fails independent from the conversion.
Maybe it's a nice to have. It also accepts user defined objects with a method isoformat.
If not, change it to, check for valid datetime types just before isoformat.


```python
class InputError(Exception):
    def __init__(self, key, value, dtype):
        self.message = 'the parameter: {}, expected a value of type {}'\
            ', got: {} with type {}'.format(key, dtype, value, type(value))

    def __str__(self):
        return repr(self.message)


def validate_userinput(extra_data):
    for key, value in extra_data.items():
        # tests allow us to run isoformat in extra_data_enc
        if isinstance(value, datetime.time):
            raise InputError(key, value, dtype='datetime.time')
        datekeywords = ['date', 'before', 'after']
        dtype = (datetime.datetime, datetime.date)
        if any([x in key.lower() for x in datekeywords]):
            if not isinstance(value, dtype):
                raise InputError(key, value, dtype)

def clean_extra_data(extra_data):
    extra_data_enc = dict()
    for key, value in extra_data.items():        
        try:
            value = str(value.isoformat())
        except (AttributeError, SyntaxError):
            """not a date"""
            pass
        try:
            int(value)
            value = str(value)
        except ValueError:
            """not an integer"""
            pass
        try:
            value.lower() +value + ''
        except:
            """final test: not a string"""
            raise InputError(key, value, str)
        extra_data_enc[key] = quote(value, safe='-_.~')

    return extra_data_enc
```

**Comment by elcolumbio** [comment]
let me run the tests. Will come back later.

**Comment by elcolumbio** [comment]
i dropped the validation part, since it's a big decision if to validate. And not so easy.

the tests are really helpful.
Since we do some cleaning and all parameter are strings.
Should i modify the tests:
```python
end_date = datetime.datetime(2018, 4, 30, 23, 59, 59)
self.assertEqual(params['EndDate'], '2018-04-30T23%3A59%3A59')
self.assertEqual(params['Acknowledged'], 'True')
```
in many cases there is no change.
@GriceTurrble

**Comment by GriceTurrble** [comment]
I mentioned it a bit in the notes of your PR for this issue, at least in terms of the boolean values. I think we should be passing all bools as either `"true"` or `"false"`, so tests would need an update to match that expectation (tip: update the tests first, then make the code pass the tests :) ).

The datetime strings are fine, either as `datetime.datetime.utcnow()` passed through `.isoformat()` or as a hard-coded date, as you've provided. Either one should pass just fine. I would have made a note about consistency in test code, but stopped myself, since test code doesn't really require consistency in structure: all it needs is a clear outline per-test of what's expected for output, and that the build can pass those tests.

**Comment by elcolumbio** [comment]
While trying to understand the mws/utils package.
I will look for some more improvements.

Like this
https://github.com/python-amazon-mws/python-amazon-mws/blob/77a116f26d4578813ae8a73420e2e88f00d2d4f2/mws/utils.py#L274

**Comment by GriceTurrble** [comment]
#67 merged: issue resolved. Thank you kindly.
