### ISSUE TITLE
Feeds API getting data

### ISSUE THREAD

**Issue by lolcats4u** [python-amazon-mws/python-amazon-mws#62]
I've been trying to get the data out of the get_feed_submission list here:
feedlist = feeds_api.get_feed_submission_list
for which there is the normal object response at some address...
<bound method Feeds.get_feed_submission_list of <mws.mws.Feeds object at 0x11a586080>>

However whenever I try to get the data using the usual methods I can't seem to get them to work.
something = feedlist.response
AttributeError: 'function' object has no attribute 'response'
something1 = feedlist.original
AttributeError: 'function' object has no attribute 'original'
somehting2 = feedlist.parsed
AttributeError: 'function' object has no attribute 'parsed'

so I was wondering how to get the data from this feeds object

**Comment by Bobspadger** [comment]
I've only got the following in my codebase (`submit_feed`) but I think it should be the same.

```python
    result = feeds_api.submit_feed(feed_data, '_POST_FLAT_FILE_INVLOADER_DATA_')
    # store feedsubmissionID
    feed_submission_id = result.parsed['FeedSubmissionInfo']['FeedSubmissionId']['value']
    feed_submission_status = result.parsed['FeedSubmissionInfo']['FeedProcessingStatus']['value']
```

**Comment by GriceTurrble** [comment]
I assume your instance of the `Feed` API class is `feeds_api`. In which case, `.get_feed_submission_list()` is a method of this class.

Here is current code for that method in `master` branch:

https://github.com/python-amazon-mws/python-amazon-mws/blob/6c67339c5a1f99937c60f809526ce06a4ada460e/mws/mws.py#L353-L369

*Note*: On 1.0 release, we're planning some changes to argument names across the board. Following is the set of arguments as they currently appear on `develop` branch:

https://github.com/python-amazon-mws/python-amazon-mws/blob/6e838f950693225360b9c3a202c676fae14a0e25/mws/apis/feeds.py#L47-L49

---

As you can see from your errors:

    somehting2 = feedlist.parsed
    AttributeError: 'function' object has no attribute 'parsed'

You are attempting to operate on the function object `feeds_api.get_feed_submission_list`. Instead, you will need to call that method, using `feeds_api.get_feed_submission_list(...)`, replacing `...` with any of the above arguments you'd like.

See [MWS documentation for the GetFeedSubmissionList method](http://docs.developer.amazonservices.com/en_US/feeds/Feeds_GetFeedSubmissionList.html) for what Amazon expects for the different data points.
