### ISSUE TITLE
Please beautify the parsed dict object :)

### ISSUE THREAD

**Issue by archtaurus** [python-amazon-mws/python-amazon-mws#69]
This mws package shall help a lot of Python programmers  a lot.
So, please beautify the parsed dict object :)

- What are so many `'value': '\n        '` for?
-  ` 'NumberOfItemsShipped': 0,` is much better than ` 'NumberOfItemsShipped': {'value': '0'},`
- `'CreatedBefore': {'value': '2018-05-17T07:00:00Z'}`  => `'CreatedBefore': '2018-05-17T07:00:00Z'`

My dict lokks like:
```
   {'value': '\n        ',
    'LatestShipDate': {'value': '2018-05-17T06:59:59Z'},
    'OrderType': {'value': 'StandardOrder'},
    'PurchaseDate': {'value': '2018-05-16T19:46:17Z'},
    'AmazonOrderId': {'value': '113-8006225-0697855'},
    'IsReplacementOrder': {'value': 'false'},
    'LastUpdateDate': {'value': '2018-05-16T19:46:22Z'},
    'NumberOfItemsShipped': {'value': '0'},
    'ShipServiceLevel': {'value': 'SecondDay'},
    'OrderStatus': {'value': 'Pending'},
    'SalesChannel': {'value': 'Amazon.com'},
    'IsBusinessOrder': {'value': 'false'},
    'NumberOfItemsUnshipped': {'value': '1'},
    'PaymentMethodDetails': {'value': '\n          ',
     'PaymentMethodDetail': {'value': 'Standard'}},
    'IsPremiumOrder': {'value': 'false'},
    'EarliestShipDate': {'value': '2018-05-17T06:59:59Z'},
    'MarketplaceId': {'value': 'ATVPDKIKX0DER'},
    'FulfillmentChannel': {'value': 'AFN'},
    'PaymentMethod': {'value': 'Other'},
    'IsPrime': {'value': 'false'},
    'ShipmentServiceLevelCategory': {'value': 'SecondDay'},
    'SellerOrderId': {'value': '113-8006225-0697855'}}]},
 'CreatedBefore': {'value': '2018-05-17T07:00:00Z'},
```

**Comment by archtaurus** [comment]
I am using Python3.6

**Comment by Bobspadger** [comment]
`object.parsed.LatestShipDate`

will give `2018-05-17T06:59:59Z`


you can also use the .get() method

`object.parsed.get('LatestShipDate')`

**Comment by archtaurus** [comment]
Thanks for reply.

Following is what I did for now, it give me a list of orders:

```python
    orders = []
    next_token = None
    while next_token == "":
        response = orders_api.list_orders(marketplaceids=MARKETPLACE_ID,
                                          created_after=created_after,
                                          created_before=created_before,
                                          next_token=next_token)
        xml_data = xmltodict.parse(response.original,
                                   process_namespaces=True,
                                   namespaces={'https://mws.amazonservices.com/Orders/2013-09-01': None,
                                               '@xmlns': None})
        if next_token is None:
            data = xml_data.get("ListOrdersResponse", {}).get("ListOrdersResult", {})
        else:
            data = xml_data.get("ListOrdersByNextTokenResponse", {}).get("ListOrdersByNextTokenResult", {})
        orders.extend(data.get("Orders", {}).get("Order", []))
        next_token = data.get("NextToken", "")

    return orders
```

Sample: 
```python
[
    {
        "LatestShipDate": "2018-05-17T06:59:59Z",
        "OrderType": "StandardOrder",
        "PurchaseDate": "2018-05-16T08:49:19Z",
        "IsReplacementOrder": "false",
        "LastUpdateDate": "2018-05-17T22:51:19Z",
        "AmazonOrderId": "112-8535118-0201056",
        "BuyerEmail": "ypk7b73g62gtgcd@marketplace.amazon.com",
        "NumberOfItemsShipped": "1",
        "ShipServiceLevel": "SecondDay",
        "OrderStatus": "Shipped",
        "SalesChannel": "Amazon.com",
        "IsBusinessOrder": "false",
        "NumberOfItemsUnshipped": "0",
        "PaymentMethodDetails": {
            "PaymentMethodDetail": "Standard"
        },
        "BuyerName": "Arianne A Rivera",
        "IsPremiumOrder": "false",
        "OrderTotal": {
            "CurrencyCode": "USD",
            "Amount": "49.99"
        },
        "EarliestShipDate": "2018-05-17T06:59:59Z",
        "MarketplaceId": "ATVPDKIKX0DER",
        "FulfillmentChannel": "AFN",
        "PaymentMethod": "Other",
        "ShippingAddress": {
            "City": "Denver",
            "PostalCode": "80235",
            "StateOrRegion": "CO",
            "CountryCode": "US",
            "Name": "Arianne Rivera",
            "AddressLine1": "3651 S. Harlan St."
        },
        "IsPrime": "false",
        "ShipmentServiceLevelCategory": "SecondDay",
        "SellerOrderId": "112-8535118-0201056"
    },
    {
        "LatestShipDate": "2018-05-17T06:59:59Z",
        "OrderType": "StandardOrder",
        "PurchaseDate": "2018-05-16T09:19:12Z",
        "IsReplacementOrder": "false",
        "LastUpdateDate": "2018-05-17T00:53:10Z",
        "AmazonOrderId": "112-1773114-3581046",
        "BuyerEmail": "qn3jcflqv9q1zh3@marketplace.amazon.com",
        "NumberOfItemsShipped": "1",
        "ShipServiceLevel": "SecondDay",
        "OrderStatus": "Shipped",
        "SalesChannel": "Amazon.com",
        "IsBusinessOrder": "false",
        "NumberOfItemsUnshipped": "0",
        "PaymentMethodDetails": {
            "PaymentMethodDetail": "Standard"
        },
        "BuyerName": "Chelsea generelli",
        "IsPremiumOrder": "false",
        "OrderTotal": {
            "CurrencyCode": "USD",
            "Amount": "50.34"
        },
        "EarliestShipDate": "2018-05-17T06:59:59Z",
        "MarketplaceId": "ATVPDKIKX0DER",
        "FulfillmentChannel": "AFN",
        "PaymentMethod": "Other",
        "ShippingAddress": {
            "City": "leechburg",
            "PostalCode": "15656",
            "StateOrRegion": "pa",
            "CountryCode": "US",
            "Name": "Chelsea generelli",
            "AddressLine1": "110 2nd street"
        },
        "IsPrime": "false",
        "ShipmentServiceLevelCategory": "SecondDay",
        "SellerOrderId": "112-1773114-3581046"
    },
#......
]
```

**Comment by agritheory** [comment]
@archtaurus Please edit the customer details out of your message.

**Comment by agritheory** [comment]
> We do not necessarily need to have this kind of edge case define the general behavior, of course: we can look into augmenting the XML2Dict parser so that nodes with only the value key are altered to produce the literal value (this would, at the same time, handle corner cases where using .get() produces the dict with {'value': ...} instead of the literal value, which is a problem mentioned in my notes on #35 ).
> That might be a bit easier said than done, however. To handle the edge case, we'd need to ensure no other keys are present aside from 'value', which may not be possible mid-way through the parsing process: we may need to implement a second-pass parser that corrects the issue.

If if it only catches that most common case that you point out, I think it's an improvement. It is not very readable this way.

**Comment by archtaurus** [comment]
Thank for all replies.  I hope I was understood. I am really not understading why all dict values are built into a  {"value": "value"} thing, and they can be more strange like:
```python
{
  ("this is a real key name", "the key name"): {"value": "blabla" },
}
```

**Comment by Bobspadger** [comment]
Straight to JSON is not really more pythonic, a dictionary IS pythonic , JSON is a serialisation formate so it would be XML -> JSON -> Python Dict, currently its XML -> Python Dict, then you can handle this as you see fit.

Direct to JSON would not give any benefit I can see (for the 30 seconds I've thought of it) as you can access the ObjectDict like JSON

```
r = result.parsed

print(r['key'])
print(r.key)
```
you can iterate etc through here. Or have I missed the point ?

**Comment by GriceTurrble** [comment]
There may be a use-case for ensuring that parsed contents can be easily serialized as a JSON string, in case a user wants to use the connector as part of their own RESTful API. The primary use-case of a Python `dict`-like object should not be superseded, though.

To the code sample on @Bobspadger 's last comment, this circles back on the topic at hand: `r['key']` will currently produce `{'value': "foobar"}`, while `r.key` will produce `"foobar"`. I'm generally agreeing that this is a problem, as it produces ugly output, wastes [admittedly small amounts of] memory, and breaks some functionality (cannot easily use `.get()`, as mentioned, without adding more to account for it, which is a bandaid on a root problem).

**Comment by GriceTurrble** [comment]
@archtaurus Noting your code sample above, I've been thinking about adding [`xmltodict`](https://pypi.org/project/xmltodict/) as a requirement, anyway. We've inherited a built-in implementation with the `utils.XML2Dict` class, but that is not something we should really be focused on maintaining, I would say.

Would you be willing to make a PR for that change? Specifically so that our `response.parsed` would now be populated by the result of `xmltodict.parse(...)`.

**Comment by agritheory** [comment]
@Bobspadger This I think is an excellent meta sort of discussion what is "pythonic". Reading the Zen of Python (sorry for the pedantry, I swear I'm a nice person) I think there are more arguments for something more JSON-y - like the output above - than for the as-is format.

**Comment by Bobspadger** [comment]
@agritheory yes very much so.

I'm not a fan of the objectdict at all to be honest - I just wasn't quite understanding why we would need to go via Json , to give pretty much the same result of a dict like object.

@GriceTurrble hit the nail on the head with

> r['key'] will currently produce {'value': "foobar"}, while r.key will produce "foobar"

I suppose the more pythonic argument would be along the _There should be one-- and preferably only one --obvious way to do it._
and we have 2!

tidying it up would be nice, but a conversation on the output and interface might be a good idea first, as changing the output of `r['key']` to match `r.key` or vice versa would break an awful lot of thing for users :) (me included!)

**Comment by elcolumbio** [comment]
Those nested data structures are often not so intuitive. I did spend weeks on the output of the finance api.
I can help you if needed.
First of all there is no right way to alter nested data, also best i guess keep it nested.
What often feels right is close to flattened tables. For reference you can find most data in flattened form in the seller central. Which are not always nice.  Since some data is badly represented in exactly those tables.

I will try to understand it.
The examples from @archtaurus are more intuitive.
The missing edge cases introduced by @GriceTurrble are probably resolved to:

``` python
>>> response.parsed.Products.Product.AttributeSets.ItemAttributes
[
   { 'Creator': 'GrandPrÃ©, Mary',
    'Role': 'Illustrator'}
]
```
How we achive this and is it an improvement at all?
honestly i am just biased. That's a pandas dataframl like structure. Otherwise i probably wouldn't like it.

**Comment by elcolumbio** [comment]
If we use xmltodict, we best use [this flag](
https://github.com/martinblech/xmltodict/issues/28)

**Comment by elcolumbio** [comment]
i attempt to fix it. Found out that it's actually a xml format. It's not messy, it's cdata. If you read the [first sentence](https://stackoverflow.com/a/2784200) you get a big aha moment.
Right now first thing we do is remove the namespace, which makes it a mess afterwards.

**Comment by elcolumbio** [comment]
What is the difference between xmltodict and the old thing?

New vs old Syntax. Those are the same.
'value' = '#text'
'Units' = '@Units'
I refer too the last ones since they are the normal syntax.

Can we simulate our old parsing in xmltodict?
No but we get close with the flag: force_cdata=True
**Attention this is not how i implemented it in #75**
But we could use it as option.

This matches our behavior right now, except where there is actual cdata.
Those are the cases @GriceTurrble referenced as edge cases = cdata.
Example old for actual cdata:
'Length': {'Units': {'value': 'inches'}, 'value': '9.00'},
Example new  for actual cdata:
{'#text': '2.80', '@Units': 'inches'}

The new Example looks the same for force_cdata=False.
So xmltodict detects cdata and our old version forces blindly cdata on everything, even on the #text of cdata which leads to #text{#text: -> that is wrong. It's the price of the easy fix in our old version.

**Comment by elcolumbio** [comment]
What you can to with cdata?
I guess a lot you can confirm that you got your expected unit. Like inches.
And omit it.
Or you can use it in your table names.
There i made a flattener which is useful:
```python
import collections

def flatten(d, parent_key='', sep='.'):
    items = []
    if len(d.keys()) == 2 and d.get('#text') and d.get('@Units'):
        units = d.get('@Units')
        cdata_key = f'{parent_key}_in_{units}'
        cdata_value = d.get('#text')
        items.append((cdata_key, cdata_value))
    else:
        for k, v in d.items():
            new_key = parent_key + sep + k if parent_key else k
            if isinstance(v, collections.MutableMapping):
                items.extend(flatten(v, new_key, sep=sep).items())
            else:
                items.append((new_key, v))
    return dict(items)
```
which is returning cdata, like that:
```python
'GetMatchingProductResult.Product.AttributeSets.ItemAttributes.PackageDimensions.Height_in_inches': '2.80',
 'GetMatchingProductResult.Product.AttributeSets.ItemAttributes.PackageDimensions.Length_in_inches': '9.75',
```

**Comment by GriceTurrble** [comment]
This ties into the work @elcolumbio has been putting in on #75 , thus is part of the 1.0 plan.

**Comment by GriceTurrble** [comment]
#207 introduction of `xmltodict` dependency and the new `DotDict` object handles this, and will be going forward into `develop` branch soon enough.
