### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by elcolumbio** [python-amazon-mws/python-amazon-mws#77]
How do you want to access the response?

First of all good news the code gets a lot easier. You could see a lot of places where it wasn't understood correctly.
For example the parsed method is doing nothing for reports, it's just passing on a string, or bytes. From now on only a better encoded string.

A. For the request.response object resolve duplicates choose one of:
1. self.original
2. self.response

B. Default:
1. use self.parsed no matter what, aka """Recieve a nice formatted response, this can be your default."""
2. dependent on text and xml. Since text we dont parse we just access it with request.original.text

C. For XML Data we provide more options:
1. a python dictionary, we can name it pydict , should it also get a parsed method?

additional:
headers object

**Comment by GriceTurrble** [comment]
#207 is cleaning up a lot of this by introducing `MWSResponse` to replace `DictWrapper` and `DataWrapper`, based partly on #75 changes that have finally been retooled and implemented. Please see docs related to that PR.
