### ISSUE TITLE
response.parsed is None when querying Reports API

### ISSUE THREAD

**Issue by nateshmbhat** [python-amazon-mws/python-amazon-mws#78]
The response.original and response.response.text both return the correct response but the response.parsed returns None . 

When I manually converted using `mws.utils.XML2Dict().fromstring( reponse.oriiginal)` i got the parsed result. 

I had used the Reports API with Report Type as : `_GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_`

**Comment by elcolumbio** [comment]
Thank you. That just helped me big times.
For XML reports from the method get_reports() it right now probably never works. That's no good.
Fixed that.

**Comment by nateshmbhat1** [comment]
One more bug I found is that when I use ur object of Report class more than once, the second time I call get_report , it gives me error saying key error : 'original'. This resolves if I use a new object for getting every report

**Comment by elcolumbio** [comment]
Do you want to clone and test the new pull request https://github.com/innotrade24/python-amazon-mws1
That's maybe clever. I think you like it. Also it's likely that the 1.00 looks somehow more like that.
Would appreciate your feedback.

**Comment by nateshmbhat1** [comment]
Sorry my bad , it's all in the api folder.
