### ISSUE TITLE
Getting syntax error when using mws.utils.XML2Dict().fromstring

### ISSUE THREAD

**Issue by nateshmbhat** [python-amazon-mws/python-amazon-mws#79]
Getting syntax error when I manually call the mws.utils function  (Since i got response.parsed as None) 

```
Traceback (most recent call last):

  File "<ipython-input-126-6b6416847cb5>", line 64, in get_all_orders
    parsedstring = (mws.utils.XML2Dict().fromstring(resp.response.text))

  File "/home/natesh/Desktop/AMAZON_MWS/src/mws/utils.py", line 106, in fromstring
    text = ET.fromstring(str_)

  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: syntax error: line 1, column 0
```

The syntax error happens because of this kind of non xml response in response.origianl = 
`b'Date range exceeded. Report can be requested only upto 30 days\r\n'`

**Comment by elcolumbio** [comment]
That's what should happen.

What do you want to achieve?
All i can think of is to decode that that byte object.

you can do it with response.original.text

**Comment by GriceTurrble** [comment]
`XML2Dict` has been deprecated and will be replaced, pending #207 .
