### ISSUE TITLE
missing GetMyFeesEstimate

### ISSUE THREAD

**Issue by hyusetiawan** [python-amazon-mws/python-amazon-mws#81]
looked around the docs and the source code, seems like this method is missing?

https://docs.developer.amazonservices.com/en_US/products/Products_GetMyFeesEstimate.html

**Comment by GriceTurrble** [comment]
We are in the process of running up to a 1.0 release, but indeed, this
method of the Products API is still missing on develop. Will work on that
shortly. :)

**Comment by personalt2** [comment]
I was able to get a single asin version of this working with code below.  

`def get_my_fee_estimate(self, marketplaceid, asin, price, currencycode, isamazonfulfilled):
        data = dict(Action='GetMyFeesEstimate')
        data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.1.Identifier.', asin))
        data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.1.IdType.', 'ASIN'))
        data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.1.IdValue.', asin))
        data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.1.MarketplaceId.', marketplaceid))
        data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.ListingPrice.Amount', price))
        data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.ListingPrice.CurrencyCode', currencycode))
        data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.1.IsAmazonFulfilled.', isamazonfulfilled))
        return self.make_request(data)`

**Comment by chilcom** [comment]
For more than one ASIN:

`def get_my_fee_estimate(self, marketplaceid, items_list, isamazonfulfilled):`
	`     data = dict(Action='GetMyFeesEstimate')`

	ix=1
	for item in items_list:
		i = str(ix)
		data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.'+i+'.Identifier.', item[0]))
		data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.'+i+'.IdType.', 'ASIN'))
		data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.'+i+'.IdValue.', item[0]))
		data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.'+i+'.MarketplaceId.', marketplaceid))
		data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.'+i+'.PriceToEstimateFees.ListingPrice.Amount', item[1]))
		data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.'+i+'.PriceToEstimateFees.ListingPrice.CurrencyCode', item[2]))
		data.update(utils.enumerate_param('FeesEstimateRequestList.FeesEstimateRequest.'+i+'.IsAmazonFulfilled.', isamazonfulfilled))
		ix = ix + 1

	return self.make_request(data)

**Comment by chilcom** [comment]
Supports up to 6 ASINs (I'm getting a server error when sending more than 6... not sure why)

**myfile.py**
items_list = []
for row in cursor.fetchall():
        item = [row[0],str(row[1]),row[2]]
        items_list.append(item)
...
            products = products_api.get_my_fee_estimate(marketplace_usa,items_list,"true")

**mws.py**
def get_my_fee_estimate(self, marketplaceid, items_list, isamazonfulfilled): data = dict(Action='GetMyFeesEstimate') ix=1 for item in items_list: i = str(ix) data.update({'FeesEstimateRequestList.FeesEstimateRequest.'+i+'.Identifier': item[0]}) data.update({'FeesEstimateRequestList.FeesEstimateRequest.'+i+'.IdType': 'ASIN'}) data.update({'FeesEstimateRequestList.FeesEstimateRequest.'+i+'.IdValue': item[0]}) data.update({'FeesEstimateRequestList.FeesEstimateRequest.'+i+'.MarketplaceId': marketplaceid}) data.update({'FeesEstimateRequestList.FeesEstimateRequest.'+i+'.PriceToEstimateFees.ListingPrice.Amount': item[1]}) data.update({'FeesEstimateRequestList.FeesEstimateRequest.'+i+'.PriceToEstimateFees.ListingPrice.CurrencyCode': item[2]}) data.update({'FeesEstimateRequestList.FeesEstimateRequest.'+i+'.IsAmazonFulfilled': isamazonfulfilled}) ix = ix + 1 return self.make_request(data)

**Comment by david-a** [comment]
@chilcom it supports up to 6-7 asins because you're using a GET request (which is the default of `make_request`) with url params. When the url gets too long I guess it truncates the url thus causing a 500 server error.
I've successfully managed to get 20 ASINs using a POST request, though I had to patch `make_request` a bit in order to do so. I guess it's somehow possible to use the original `make_request` with this POST request but it was much easier for me to just patch it.
This is my code (more or less.. I've added those functions in my code as polyfills instead of patching the `python-amazon-mws` PiP itself)

```
def get_my_fees_estimate(products_api, marketplace_id, items_list, id_type = 'ASIN', is_amazon_fulfilled = True):
    data = dict(Action = 'GetMyFeesEstimate')
    for i, item in enumerate(items_list, start = 1):
        data["FeesEstimateRequestList.FeesEstimateRequest.{}.Identifier".format(i)] = item[0]
        data["FeesEstimateRequestList.FeesEstimateRequest.{}.IdType".format(i)] = id_type
        data["FeesEstimateRequestList.FeesEstimateRequest.{}.IdValue".format(i)] = item[0]
        data["FeesEstimateRequestList.FeesEstimateRequest.{}.MarketplaceId".format(i)] = marketplace_id
        data["FeesEstimateRequestList.FeesEstimateRequest.{}.PriceToEstimateFees.ListingPrice.Amount".format(i)] = str(item[1]) # Landed price
        data["FeesEstimateRequestList.FeesEstimateRequest.{}.PriceToEstimateFees.ListingPrice.CurrencyCode".format(i)] = item[2]
        data["FeesEstimateRequestList.FeesEstimateRequest.{}.IsAmazonFulfilled".format(i)] = str(is_amazon_fulfilled).lower()

    return mws_post(products_api, data)

def mws_post(api, body, **kwargs):
    body = mws.mws.remove_empty(body)
    method = 'POST'

    for key, value in body.items():
        if isinstance(value, (datetime, date)):
            body[key] = value.isoformat()

    params = api.get_params()
    params.update(body)
    request_description = mws.mws.calc_request_description(params)
    signature = api.calc_signature(method, request_description)
    params['Signature'] = signature
    url = "{domain}{uri}".format(
        domain=api.domain,
        uri=api.uri
    )
    headers = {'User-Agent': 'python-amazon-mws/0.8.6 (Language=Python)'}
    headers.update(kwargs.get('extra_headers', {}))

    try:
        response = request(method, url, data=params, headers=headers)
        response.raise_for_status()
        data = response.content
        rootkey = kwargs.get('rootkey', body.get("Action") + "Result")
        try:
            try:
                parsed_response = mws.mws.DictWrapper(data, rootkey)
            except TypeError:
                parsed_response = mws.mws.DictWrapper(response.text, rootkey)

        except XMLError:
            parsed_response = mws.mws.DataWrapper(data, response.headers)

    except HTTPError as e:
        error = MWSError(str(e.response.text))
        error.response = e.response
        raise error

    # Store the response object in the parsed_response for quick access
    parsed_response.response = response
    return parsed_response
```

where `products_api` is the object return from `mws.Products`.

**Comment by JasonCrowe** [comment]
Here is my function (added to mws.py):
```
    def get_my_fee_estimate(self, marketplaceid, item, isamazonfulfilled):
        data = dict(Action='GetMyFeesEstimate')
        data.update({'FeesEstimateRequestList.FeesEstimateRequest.1.Identifier': item})
        data.update({'FeesEstimateRequestList.FeesEstimateRequest.1.IdType': 'ASIN'})
        data.update({'FeesEstimateRequestList.FeesEstimateRequest.1.IdValue': item})
        data.update({'FeesEstimateRequestList.FeesEstimateRequest.1.MarketplaceId': marketplaceid})
        data.update({'FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.ListingPrice.Amount': item})
        data.update({'FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.ListingPrice.CurrencyCode': 'USD'})
        data.update({'FeesEstimateRequestList.FeesEstimateRequest.1.IsAmazonFulfilled': isamazonfulfilled})
        return self.make_request(data)
```

When I try this I get the following error:
`TypeError: quote_from_bytes() expected bytes`

Any ideas why it wouldn't be returning correctly?

**Comment by jasonhdavis** [comment]
Just expressing interest in development of this function

**Comment by Bobspadger** [comment]
I've added it to the roadmap as it would be nice to be feature complete.

Any takers for working on it?

**Comment by GriceTurrble** [comment]
This has been added to `develop` version recently in #220 , making it available and feature-complete.

There will be no backporting this call to `master` / 0.8 version, however, so use of the 1.0dev versions is required.

Sorry for the wait! 😁
