### ISSUE TITLE
flatten the response

### ISSUE THREAD

**Issue by elcolumbio** [python-amazon-mws/python-amazon-mws#82]
Like @GriceTurrble  said that is after 1.0.
Still it maybe useful right now.

A flattener is really nice for the nested data.
[This one](https://github.com/innotrade24/mwstools) is not perfect but it does some magic.
It works only with #75.

**Comment by GriceTurrble** [comment]
I do not see the use case in offering a "flattened" response. Can you elaborate, please?

**Comment by elcolumbio** [comment]
To me it seems there are only a very few open source project doing this.
A bit familiar is this: https://better.engineering/jsonschema2db/
I don't know how domain specific this is to loans.
But like them i could improve it to auto generate SQL like tables, or panda dataframes.
Tough it's always better to validate against a schema.

I can close it for now since there seems to be no need for this.

**Comment by elcolumbio** [comment]
If someone reads this.
You probably want to use this:
[http://sedimental.org/remap.html](http://sedimental.org/remap.html)
Even if you end up writing your own tool.
Remap introduces some precise and easy concepts.
I did not know about it when i made that issue.
