### ISSUE TITLE
Missing required parameter SellerId.

### ISSUE THREAD

**Issue by anuj9196** [python-amazon-mws/python-amazon-mws#85]
I'm listing categories of the product using ASIN
```
products_api = mws.Products(
        access_key=settings.MWS_CLIENT_KEY,
        secret_key=settings.MWS_CLIENT_SECRET,
        account_id=settings.MWS_SELLER_ID,
        region='US'
    )

    products = products_api.get_product_categories_for_asin(
        marketplaceid=settings.MWS_MARKETPLACE_ID,
        asin=asin,
    )

    print(products)
```

But this is giving error

```
mws.mws.MWSError: <?xml version="1.0"?>
<ErrorResponse xmlns="http://mws.amazonservices.com/schema/Products/2011-10-01">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>Missing required parameter SellerId.</Message>
  </Error>
  <RequestID>ebc6f742-43b5-4f98-b681-974599284db7</RequestID>
</ErrorResponse>
```

I tried same credentials with https://mws.amazonservices.com/scratchpad/index.html

and it's working fine.

**Comment by GriceTurrble** [comment]
I would have to assume from here that there is some issue with the data input. Can you confirm the following, please?

* `settings.MWS_SELLER_ID` returns the correct value.
* After setting `products_api = mws.Products(...)`, the attribute `products_api.account_id` returns the correct value.
* `products_api.get_params()` (or, if you are using develop branch, `products_api.get_default_params()`) returns a `dict` containing the key `"SellerId"` with the correct value.

If these are all working fine and you still have the issue, we can try something else from there.

**Comment by GriceTurrble** [comment]
Also, please remove the link you've posted ASAP, as it contains client details. If you want to include a screenshot, I highly suggest editing that one first.

**Comment by Bobspadger** [comment]
Quick test and its working for me:


```
from credentials import creds
import mws

SECRET_KEY = creds['amazon']['secret_key']
AWS_ACCESS_KEY = creds['amazon']['AWS_access_id']
SELLER_ID = creds['amazon']['sellerid']
MARKETPLACE_ID = creds['amazon']['marketplaceids']['UK']

products_api = mws.Products(access_key=AWS_ACCESS_KEY, secret_key=SECRET_KEY, account_id=SELLER_ID, region='UK')

result = products_api.get_product_categories_for_asin(marketplace_id=MARKETPLACE_ID, 
asin='B004A76R88') 

print(result.parsed)
{'Self': [{'ProductCategoryId': {'value': '407675031'}, 'ProductCategoryName': {'value': 'Bags, Cases & Racks'}, 'Parent': {'ProductCategoryId': {'value': '5450332031'}, 'ProductCategoryName': {'value': 'Accessories'}, 'Parent': {'ProductCategoryId': {'value': '407674031'}, 'ProductCategoryName': {'value': 'DJ & VJ Equipment'}, 'Parent': {'ProductCategoryId': {'value': '340838031'}, 'ProductCategoryName': {'value': 'Categories'}, 'Parent': {'ProductCategoryId': {'value': '340837031'}, 'ProductCategoryName': {'value': 'Musical Instruments & DJ'}}}}}}, {'ProductCategoryId': {'value': '407794031'}, 'ProductCategoryName': {'value': 'Bags, Cases & Racks'}, 'Parent': {'ProductCategoryId': {'value': '407792031'}, 'ProductCategoryName': {'value': 'PA & Stage'}, 'Parent': {'ProductCategoryId': {'value': '340838031'}, 'ProductCategoryName': {'value': 'Categories'}, 'Parent': {'ProductCategoryId': {'value': '340837031'}, 'ProductCategoryName': {'value': 'Musical Instruments & DJ'}}}}}]}
```

**Comment by anuj9196** [comment]
Yah got it solved, there was an issue with SellerId I was providing.

But Now, I'm getting two types of data

```
from .utils import get_amazon_product_category_by_asin as pca
product = products_api.get_product_categories_for_asin(
        marketplaceid=settings.MWS_MARKETPLACE_ID,
        asin='B00BX9YDE6',
    )

# Gives
{'Self': {'ProductCategoryId': {'value': '1069306'}, 'ProductCategoryName': {'value': 'Bulletin Boards'}, 'Parent': {.......}}

But with asin='B073KYQT4S'
# Gives
{'Self': [{'ProductCategoryId': {'value': '13753041'}, 'ProductCategoryName': {'value': 'Futons'}, 'Parent': ...}]}
```

Note, 2nd data contains a list under `Self` while first don't.

**Comment by Bobspadger** [comment]
Best thing to do is debug and grab the request response text (which should be XML), you can then see what Amazon returns , it will probably be that they have returned this as multiple items in there.

Copy and paste it here.

**Comment by GriceTurrble** [comment]
What you are seeing with that data is (mostly) expected. The parsed dict-like object will produce either:

* a single dict-like object when one child node is present of a given key name; or
* a list of dict-like objects when there are multiple child nodes with the same key names.

In the case of your data return, I suspect the second set of data's XML contains two entries with the `'Self'` tag, both of them children of the `'GetProductCategoriesForASINResult'` node. In this context, that would mean you have a product with multiple categories assigned.

This behavior is slightly counter-intuitive at first, but workable. You should be able to iterate* on the dict-like object by accessing it like an attribute:

```python
for self_category in product.parsed.Self:
    print(self_category.ProductCategoryId, self_category.ProductCategoryName)

# This should result in something like:
13753041 Futons
456789 NotReallyABed
```

*There is a catch with the current release code, in that a single-node value will not be iterable. This has been fixed on the current version of develop branch so it is always iterable (not yet released as we are breaking things to build to a 1.0 release); but for now, if you attempt to iterate a node that may sometimes be a single-value return, you will sometimes get an error.

To work around this, only for the time being, I recommend the following pattern:

```python
self_categories = product.parsed.Self
if not isinstance(self_categories, list):
    # wrap the single value in a list
    self_categories = [self_categories]

for self_category in self_categories :
    # do stuff with the objects
```

**Comment by Bobspadger** [comment]
I have a helper function I call on all returned data from Amazon:

```py
def listify(amazon_object):
    """
    Test if returned amazon item is a list, if not, return it as a list.

    :param amazon_object:

    :return:
    """
    if isinstance(amazon_object, list):  # pylint: disable=no-else-return
        return amazon_object
    else:
        return [amazon_object]
```

Can we call this issue closed now ?
