### ISSUE TITLE
next token decorator

### ISSUE THREAD

**Issue by elcolumbio** [python-amazon-mws/python-amazon-mws#86]
I really like that we use the decorator.
Why do we need the additional abstraction level around the NEXT_TOKEN_OPERATIONS constant?

If something like this is a lot better, i can make a pull request.
```python
def next_token_action(action_name):
            next_token = kwargs.pop('next_token', None) 
            if next_token is not None: 
                # Token captured: run the "next" action. 
                #removed: return self.action_by_next_token(action_name, next_token) 
                action = action_name + 'ByNextToken'  # new
                data = {'Action': action, 'NextToken': next_token}   # new
                return self.make_request(data, method="POST")   # new
            return request_func(self, *args, **kwargs) 
        return _wrapped_func 
    return _decorator
```

I would remove everything in mws.Mws and the NEXT_TOKEN_OPERATIONS constant.

@next_token_action('ListOrderItems')
and delete the other 3 places where we defined 'ListOrderItems'. That's not changing too much.

**Comment by elcolumbio** [comment]
For me it would be clearer. Like in the docs it says:
  Pass `next_token` to call "ListOrdersByNextToken" instead.
That's action is never defined.
Only ListOrders is defined and this 4 times! With my solution its defined 1 time and 1 time as ListOrdersByNexToken.
We also can drop defining ListOrdersByNexToken and make it dynamic, than we have ListOrders defined only once.

**Comment by elcolumbio** [comment]
ok we need to solve the self.make_request part

**Comment by elcolumbio** [comment]
in the ebayapi you can do this:
```python
m = Finding(siteid='EBAY-DE', config_file=conf)
m.execute('findItemsIneBayStores')
m.next_page()
```
Is that good or bad?
Also would be nice place to use generator?

**Comment by GriceTurrble** [comment]
`NEXT_TOKEN_OPERATIONS` was intended as a check in development to ensure that the correct operations were being sent with "next tokens". Though it complicates things slightly, the intent was preventing traffic to MWS that we know beforehand will result in an error, allowing a fast error response without having to build and transmit a request.

It's certainly not a requirement to leave it there, really just an abstraction that adds complication for a small gain.

---

As for the `ebayapi` example, I'm seeing in their example docs for that specific call that they output a page number for searches, so you would only need to get the next page by requesting "page 2" and "page 3", for instance. That simplifies their use case.

That doesn't mean we can't do the same by cleaning up the complexity, which would mean hiding the "NextToken" juggling behind the scenes, either using an iterable response object as a generator or giving the response object a `.next()` method that runs its next response.
