### ISSUE TITLE
API doesn't support AU Marketplace

### ISSUE THREAD

**Issue by SanghviChirag** [python-amazon-mws/python-amazon-mws#91]
To support AU marketplace, I think we just need to add AU 
endpoint: "https://mws.amazonservices.com.au"  # A39IBJ37TRP1C6
I didn't dig much, we need to do anything else.

Help me if there is anything else to do

**Comment by elcolumbio** [comment]
Thank you SanghviChirag.
If it's ok i implement it in my pending pull request #84.

**Comment by GriceTurrble** [comment]
That change ought to do it, thank you.

Leaving open until I finally get some time to run tests on that PR and merge it in.

**Comment by jameshiew** [comment]
The AU and BR endpoints have been added to `master` and a minor release pushed to PyPI for the time being (v0.8.6).
