### ISSUE TITLE
Accessing dict information

### ISSUE THREAD

**Issue by JasonCrowe** [python-amazon-mws/python-amazon-mws#94]
For asin:
B071Z8LD77

I am getting data with this:
`top_category = products_api.get_product_categories_for_asin(marketplaceid=marketplace_usa, asin=self.asin).parsed`

`{'Self': {'Parent': {'Parent': {'Parent': {'Parent': {'Parent': {'ProductCategoryId': {'value': '16310101'},
                                                                 'ProductCategoryName': {'value': 'Grocery & Gourmet Food'}},
                                                      'ProductCategoryId': {'value': '16310211'},
                                                      'ProductCategoryName': {'value': 'Categories'}},
                                           'ProductCategoryId': {'value': '16310231'},
                                           'ProductCategoryName': {'value': 'Beverages'}},
                                'ProductCategoryId': {'value': '16521305011'},
                                'ProductCategoryName': {'value': 'Coffee, Tea & Cocoa'}},
                     'ProductCategoryId': {'value': '16318031'},
                     'ProductCategoryName': {'value': 'Coffee'}},
          'ProductCategoryId': {'value': '14978414011'},
          'ProductCategoryName': {'value': 'Single-Serve Capsules & Pods'}}}`

My question is how can I get the top-level category from this? I know I can use:
top_category.Self.Parent.Parent.Parent.Parent.Parent.ProductCategoryName but the next asin may not have this many nested levels of 'parent'.

Any ideas?

**Comment by GriceTurrble** [comment]
I would suggest simply using a small recursive function to find the top-level category.

*Commuting at the moment; would be able to hash out some pseudocode later*

**Comment by JasonCrowe** [comment]
Thanks Grice,

I ended up not needing this. However, I would add that Beautiful Soup can be used on XML files, making this a bit easier. :)
